openstenoproject/plover

plover/orthography.py, plover/test_orthography.py
Inspired by issue #138
Warning: I wrote this on a machine without python, so it may be entirely broken
=> Try to further improve the english orthography rules

README.rst
To reach a wider audience, I think our documentation should be multilingual. I'm submitting my translation of it into Spanish :]. I can add more languages in the future if this is something we want to do.
=> Add Spanish translation of readme.

plover/gui/suggestions.py, plover/steno_dictionary.py
=> Adds multiple suggestions to Suggestions window

plover/gui/add_translation.py, plover/gui/dictionary_editor.py, plover/gui/lookup.py, plover/gui/main.py
+ one additional minor cleanup
=>  make sure main window is placed within screen boundaries

plover/machine/sidewinder.py
Don't suppress the key if arpeggiate mode is not enabled.
=> machine/sidewinder: fix arpeggiate key suppression

plover/test_translation.py, plover/translation.py
Addressing issue #105 
Adds an in-built way to handle the empty buffer. After there are no strokes in the buffer, Plover emits "Alt_L(BackSpace)" (Mac) or "Control_L(BackSpace)" (Win & Linux) in order to not halt the user. Also had to include the "{^}" operator because this kind of spacing removes the previous word, not the previous word and its space :)
Could I ask you, @chajadan, to review this? I'm looking for general code style advice, as I think this is very fringe behavior for Plover. Tell me what you think.
Ted
=> Add word deletion on empty buffer

plover/config.py, plover/test_config.py
=> config: store paths below CONFIG_DIR as relative

plover/machine/stentura.py
The while loop polling serial port buffer caused 100% CPU usage and was replaced by code that rises the timeout exception if read() method returns less bytes as requested.
=> Remove busy loop from the stentura serial port reading

osx/README.md, plover/machine/base.py, plover/machine/registry.py, plover/machine/stentura.py, plover/machine/treal.py
Using the Treal, I had to make some changes and these helped me through it.
=> Improve machine logging, clarify Mac documentation

plover/gui/keyboard_config.py, plover/oslayer/keyboardcontrol.py, plover/oslayer/winkeyboardcontrol.py
This add a capture dialog when editing a keymap entry:
=> Improve keyboard config

plover/app.py, plover/config.py, plover/dictionary/test_json_dict.py, plover/formatting.py, plover/gui/add_translation.py, plover/gui/lookup.py, plover/gui/serial_config.py, plover/machine/stentura.py, plover/machine/test_registry.py, plover/machine/test_stentura.py, plover/main.py, plover/oslayer/keyboardcontrol.py, plover/oslayer/processlock.py, plover/oslayer/winkeyboardcontrol.py, plover/steno_dictionary.py, plover/test_formatting.py, plover/test_orthography.py, plover/test_steno.py, plover/test_steno_dictionary.py, plover/test_translation.py
* remove duplicate import
* cleanup more unused imports
* fix relative imports
=> Cleanup imports

plover/log.py, plover/main.py
Make sure Plover's configuration directory exists before setting-up Plover's logfile.
=> log: fix logfile support

plover/machine/treal.py
With a more recent version of the hid module, the API has changed, and the code crashes...
=> Fix crash during treal init when not connected

plover/dictionary_editor_store.py, plover/gui/paper_tape.py, plover/gui/suggestions.py, plover/gui/util.py
paper tape:
- switch to a fixed width font
- rework controls:  change strokes list and header controls to text entries, and align them
- improve width/height calculations
- fix flickering when toggling "on top"
- do not mess with background color
suggestions:
- switch to a fixed width font
- fix flickering when toggling "on top"
- do not mess with background color
- get rid of MyStaticText hack
=> Improve paper tape and suggestions

plover/gui/config.py, plover/gui/keyboard_config.py, plover/gui/serial_config.py
The most important being the first one: `gui/keyboard_config: fix mapping editing`
For some reason on Windows, after changing a mapping, the corresponding row would not update...
=> various GUI related fixes

plover/test_translation.py, plover/translation.py
Move some functions to the Translator class, so less state has to be
passed around and it's easier to modify the behavior / subclass it.
=> translation: make code more pythonic

plover/machine/stentura.py, plover/machine/test_stentura.py
The merged pull request #200 broke the tests of stentura.py. The tests have been updated and unnecessary tests have been removed. This contains also small coding fixes in stentura.py.
=> Fix stentura tests

CONTRIBUTING.md
Also makes progress towards #261.
=> Add CONTRIBUTING.md [fixes #346]

plover/gui/config.py
Also, provide some useful feedback in case the file you are adding doesn't
exist, should fix #167. Also lets you know if the dictionary is already
present.
=> Add ability to add multiple dictionaries at a time

appveyor.yml, plover/gui/main.py, setup.py, windows/helper.py
When pushing to a "weekly" branch, a new pre-release will be automatically deployed to GitHub.
The release will looks [like this](https://github.com/benoit-pierre/plover/releases/tag/weekly-v2.5.8+344.g90c6102).
Note: the version is patched in, so the about dialog will show it.
=> update AppVeyor support so we can easily do weekly pre-releases

plover/gui/main.py
- Remove bitmaps for status indicator, as part of the effort for #263.
- Windows has a grey color for the main frame because that is Windows' default color. To fix this, you place a top-level panel in the frame.
- Add a disabled state for output status when a machine is disconnected.
- Remove status from title-bar.
- Section off the user interface for clarity, needed especially because of the status indicator.
- Show status with radio buttons.
Here is the redesign:
=> Redesign main frame

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Add Markdown templates for issues and pull requests, copying the current issue template from `contributing.md`
The templates will give a little structure and guidance, which is especially useful for new contributors. I let the PR template be very relaxed, because PRs can vary in scope/necessary detail.
=> Add issue and pull request templates

plover/dictionary_editor_store.py
Show the actual translation for each item...
Linux + Windows 10 VM.
=> gui/dictionary_editor: fix translation column contents

.travis.yml, appveyor.yml, setup.py
#401 was incorrectly targeted at weekly, resubmit for master...
=> Rework AppVeyor and Travis CI deployments

linux/README.md
Add Linux specific readme with instructions on how to install dependencies and install and run Plover.
=> add Linux specific readme

plover/main.py
=> add command line parsing (--help, --version)

plover/oslayer/winkeyboardcontrol.py
Check the active layout from the foreground window with each output, and if the keyboard layout has changed, then we reload the keyboard layout. I tried this with English and German in my regional list, then put one window in German, one in English, and switched between them. Plover had to update the layout and still got the symbols right (", @, et cetera)
@tarmean, could you verify this fixes #415 ?
- Handle changing keyboard layouts while Plover is running on Windows
Windows 7
=> winkeyboardcontrol: verify active layout on output

plover/gui/log_wx.py
=> gui/log: fix doubled messages when using wx

plover/gui/paper_tape.py
Scroll infintely in the notes window. Allow saving the notes.
Fixes #406, #125
=> Save notes

plover/gui/main.py
Tested on Linux and with a Windows 10 VM.
=> gui/main: catch exceptions on reconnect

plover/oslayer/keyboardcontrol.py
Tested on Linux. The test code does not work on Windows, but that is a separate issue.
=> oslayer/keyboardcontrol: fix test code

plover/orthography.py, plover/system/__init__.py
It seems like some of the changes for preliminary system support fell through the cracks: the orthography module was not using the system module...
=> System support

linux/README.md
Tested with a Ubuntu 14.04 LTS (Trusty Tahr) VM.
=> linux: update setup documentation for Ubuntu

plover/machine/txbolt.py
Finish the stroke on last possible key set.
=> machine/txbolt: improve finished stroke detection

plover/translation.py
Another missing change for the preliminary system support...
=> translation: use system

plover/oslayer/winkeyboardcontrol.py
Even if the keyboard capture subprocess is set as 'daemon', there is no
guarantee it will be terminated if its parent process gets violently
killed; e.g. by a signal (as Python 'atexit' code will not be executed).
This can be observed by starting Plover from source using launch.bat,
enabling output, and then interrupting the batch file with Control+C:
the main Plover process is killed, but the capture process is still
alive (and keeps on suppressing the keyboard).
This is fixed by adding some code in the subprocess to monitor its
parent: if the parent dies, the subprocess will terminate itself
automatically.
=> oslayer/winkeyboardcontrol: improve keyboard capture

plover/formatting.py, plover/machine/treal.py, test/test_formatting.py, test/test_orthography.py, test/test_passport.py, test/test_rtfcre_dict.py
* orthography: minor test code simplification
* passport: simplify test code
* formatting: tweak tests; better assert message
=> minor testsuite related changes

plover/steno_dictionary.py
Check key length before attempting lookups. I also removed the dead code for filter support.
=> steno_dictionary: minor optimisations

setup.py
This should make our AppVeyor / Travic CI builds fail again on test failure...
=> setup: fix exit code on some commands failure

plover/translation.py
=> translation: minor simplifications

plover/__init__.py, setup.py
See [official list of supported classifiers](https://pypi.python.org/pypi?:action=list_classifiers).
=> setup: fix license information

.travis.yml
We might as well dogfood our own PPA.
=> travis: use our own PPA for the wx backport

plover/config.py
Deleting and recreating a section on update will move it at the end of the configuration file, and possibly change the order of its options. Both are annoying when versioning said file.
=> config: stop recreating sections on update

plover/gui/add_translation.py
On Linux, the engine output triggers transient focus out/in events which, coupled with the fact that enabling/disabling the strokes filter is done in another thread in parallel to the machine thread, make it really unreliable.
So instead of relying on focus out events, only use focus in events to track which field is focused.
Note: that with the previous code it was possible (with the add translation dialog open) to switch focus to another window and write normally. This is not supported anymore, as we don't know the strokes/translation field lost focus, and using `EVT_KILL_FOCUS` at the dialog/window level does not work (it's never triggered, on Linux or Windows).
Tested on Linux and with a Windows 10 VM.
=> gui/add_translation: fix strokes filtering

plover/misc.py, plover/oslayer/osxkeyboardcontrol.py, plover/oslayer/osxkeyboardlayout.py, plover/oslayer/winkeyboardcontrol.py, plover/oslayer/winkeyboardlayout.py, test/test_misc.py
Fix #533 
- osxkeyboardlayout is now a class
- Useful main method that debugs the parsed layout
- Favor key combos with less modifiers
- Detect key layouts changing
=> Fix Mac OS X keyboard layout

plover/app.py, plover/dictionary/rtfcre_dict.py, plover/dictionary_editor_store.py, plover/formatting.py, plover/gui/paper_tape.py, plover/log.py, plover/machine/keyboard.py, plover/machine/stentura.py, plover/machine/treal.py, plover/oslayer/config.py, plover/oslayer/keyboardcontrol.py, plover/oslayer/processlock.py, plover/oslayer/winkeyboardcontrol.py, plover/oslayer/winkeyboardlayout.py, plover/oslayer/xkeyboardcontrol.py, plover/translation.py, setup.py, test/test_json_dict.py, test/test_key_combo.py, test/test_orthography.py, test/test_passport.py, test/test_rtfcre_dict.py, test/test_steno_dictionary.py, test/test_stentura.py, test/test_translation.py, windows/helper.py
Unused imports/variables, old-style class definitions, small formatting issues...
=> small cleanups

linux/README.md, plover/config.py, plover/dictionary/json_dict.py, plover/formatting.py, plover/gui/suggestions.py, plover/gui/util.py, plover/key_combo.py, plover/machine/stentura.py, plover/machine/treal.py, plover/machine/txbolt.py, plover/main.py, plover/misc.py, plover/oslayer/keyboardcontrol.py, plover/oslayer/osxkeyboardcontrol.py, plover/oslayer/osxkeyboardlayout.py, plover/oslayer/winkeyboardcontrol.py, plover/oslayer/winkeyboardlayout.py, plover/oslayer/xkeyboardcontrol.py, plover/steno_dictionary.py, plover/translation.py, setup.py, test/test_formatting.py, test/test_rtfcre_dict.py, test/test_stentura.py, utils/metadata.py, windows/helper.py
* do not use `dict.iteritems()`
* do not use `xrange`
* use `print()`
* use `//` instead of `/` when applicable
=> some preliminary "safe" changes for Python 3 support

README.rst
Add master build status badges for AppVeyor and Travis CI.
=> readme: add status badges

plover/steno_dictionary.py, test/test_steno_dictionary.py
Don't stop at the first dictionary with matches: return all possible strokes in all dictionaries (ignoring strokes overridden in higher precedence dictionaries).
=> steno_dictionary: improve reverse lookup

plover/oslayer/winkeyboardcontrol.py
The heartbeat thread needs to be stopped before exit, or with Python 3 the process will deadlock at exit trying to join it.
=> oslayer/winkeyboardcontrol: fix capture process termination

plover/machine/txbolt.py
This low timeout has been causing splitting issues. I'd like to revert to the previous value and solve this later in #599
=> Revert "Reduce timeout for TX Bolt protocol"

setup.py
Add Python 3 and the detail of minor versions that are actually tested on AppVeyor / Travis.
=> setup: update classifiers

.travis.yml, setup.cfg
* create only one [universal wheel](https://packaging.python.org/distributing/#universal-wheels).
* add source distribution: same as the GitHub release with some additional metadata, it will be uploaded to PyPi and used for the signed Ubuntu package available on the PPA.
=> Tweak release artifacts

plover/oslayer/xkeyboardcontrol.py
The select system call can be interrupted (e.g. because of a signal), when using Python <=3.5, and must be retried (Python 3.5 already automatically retries interrupted system calls).
The logic was tested with Python 2.7/3.4/3.5 using this [script](https://gist.github.com/anonymous/3b366a4dd564c6c82a5bbf03fab50a76).
=> oslayer/xkeyboardcontrol: fix handling of interrupted select call

plover/gui_qt/paper_tape.py
Automatically save/restore the paper tape style.
=> gui_qt/paper_tape: add style to the settings

plover/gui_qt/main_window.py, plover/gui_qt/main_window.ui, plover/gui_qt/messages/fr/LC_MESSAGES/plover.po
Behave as the "{PLOVER:FOCUS}" command.
=> gui_qt/main_window: change "Show/Hide" to "Show" only

plover/config.py, plover/dictionary/base.py, plover/gui_qt/dictionaries_widget.py, plover/registry.py, plover/steno_dictionary.py, setup.py
Add support for dictionary plugins, e.g. [plover_python_dictionary](https://github.com/benoit-pierre/plover_python_dictionary) add support for Python dictionaries.
=> Plugins support: dictionaries

plover/gui_qt/add_translation.py, plover/gui_qt/config_window.py, plover/gui_qt/dictionaries_widget.py, plover/gui_qt/dictionary_editor.py, plover/gui_qt/lookup_dialog.py, plover/gui_qt/main_window.py, plover/gui_qt/main_window.ui, plover/gui_qt/paper_tape.py, plover/gui_qt/suggestions_dialog.py, plover/gui_qt/tool.py, plover/gui_qt/utils.py, plover/registry.py, setup.py
- use the plugins support so new tools can be added
- allow customizing which tools are shown in the toolbar:
=> gui_qt: refactor how tools are handled

debian/control, debian/rules, linux/README.md, osx/README.md
- update Linux / OS X instructions (Note: I removed the "running from egg" option as it seems that importing from eggs is not thread-safe...)
- fix Debian package rules (test command and assorted dependencies)
=> Miscellanous fixes

plover/formatting.py, test/test_blackbox.py
=> Allow forcing lowercase in title case output mode

plover/gui_qt/lookup_dialog.py, plover/gui_qt/suggestions_dialog.py, plover/gui_qt/suggestions_widget.py
Append suggestions to the widget instead of prepending, to avoid reported slowdowns after a while.
=> gui_qt/suggestions: append instead of prepending

plover/gui_qt/config_serial_widget.ui
Fix serial port/timeout configuration (fix #676).
=> Config window fixes

plover/gui_qt/config_window.py, plover/machine/keymap.py, test/test_keymap.py
Add some long overdue tests for the keymap code, and fix #659.
=> Fix keymap editing

plover/gui_qt/main_window.py
Use the same icon as for the main application window.
=> gui_qt: fix tools window icon

plover/machine/txbolt.py
=> Fix TX Bolt keymap handling

plover/config.py, plover/engine.py, plover/machine/treal.py, plover/oslayer/xkeyboardcontrol.py, plover/steno.py, test/test_passport.py
Remove dead code, a few trailing spaces, and fix some bad indentations...
=> minor cleanups

plover/gui_qt/engine.py
Hopefully this should take care of #648.
=> gui_qt: disable Mac's App Nap in the engine thread

plover/gui_qt/dictionary_editor.py
Avoid using indexes while the model data is being modified. Fix #678.
=> gui_qt/dictionary_editor: fix potential crashes

launch.sh, linux/debuild.sh, test.sh
=> Fix launch.sh to work on macOS

plover/engine.py, plover/resource.py, utils/install_wheels.py, windows/helper.py
The resulting list will have at most `maxsplits+1` entries, not `maxsplits`...
=> Fix use of str.split maxsplits

test/test_blackbox.py
Rework blackbox tests to make it easier to add new ones. Also add tests for bug:
- #719:  pass on master, so it can be closed
- #741: xfail
=> rework blackbox tests

.travis.yml
I forgot to update the path to the build script after adding install support.
=> travis: fix AppImage creation

plover/gui_qt/config_window.py
Look at the machine class, so it's possible to develop machine plugins that are not serial based, like the Tréal, or alternative keyboard machines.
=> gui_qt/config: improve handling of machine specific options

plover/main.py
This will allow access to plugins/packages scripts when running from a distribution.
=> main: add support for running console scripts

plover/gui_qt/resources/resources.qrc
=> gui_qt: drop missing suggestions.svg from resources

ci/travis.sh
Fix [error](https://travis-ci.org/benoit-pierre/plover/jobs/246504298#L955) when building dbus-python.
=> travis: fix build

plover/config.py, requirements.txt
* fix config deprecation warning
* update pytest requirement to fix remaining testsuite warnings
=> Fix testsuite warnings

plover/engine.py, plover/gui_none/engine.py, plover/gui_none/main.py, plover/gui_qt/engine.py, plover/gui_qt/main.py, plover/gui_qt/main_window.py, plover/main.py, setup.py, test/test_engine.py
To be used by the plugin manager. Tested on Linux and with Windows 10 VM.
=> add support for restarting

application/plover.desktop
Reference: https://travis-ci.org/AppImage/AppImageHub/builds/266233268#L545
=> Make it pass desktop-file-validate

setup.py
Broken when support for restarting was added.
=> setup: fix launch command not auto-building anymore

requirements_plugins.txt
This will fix support for updating/downgrading system plugins.
=> plugins: update plover-plugins-manager to latest version

requirements.txt, requirements_distribution.txt, requirements_plugins.txt, setup.cfg
* PyObjC: 4.0 has been released
* pyserial: better handling of blocking errors and EINTR
* python-xlib: performance improvements
* wheel
=> Update some requirements

plover/main.py, plover/oslayer/config.py, plover/registry.py, setup.py
Update Python version to 3.6.3. This fix the AppVeyor build.
=> windows: fix distribution creation

plover/gui_qt/dictionary_editor.py
=> gui_qt/dictionary_editor: clear selection on filter updates

plover/assets/commands.json
Update dictionary with feedback from #400 as well as updates to my own and Mirabai's personal dictionaries.
The PR still needs a quick review to make sure none of the changes were made in error (by me), and I'll also want to make sure that the entries I wrote by hand are in steno order and have not checked that yet.
=> Update dictionary with feedback from issue 400

plover/formatting.py, test/test_blackbox.py
=> formatting: fix trailing space handling

requirements_distribution.txt
So we can get the latest bugfix release for 5.9.
=> update PyQt5 requirement

plover/formatting.py, plover/gui_qt/suggestions_dialog.py
=> Fix suggestions

plover/translation.py, test/test_translation.py
=> translation: fix support for undoing multiple translations

setup.py
The current working directory was not prepended to the Python path, making it impossible to install some packages from source.
=> windows: fix distribution environment

plover/gui_qt/machine_options.py, plover/machine/base.py, plover/machine/passport.py
=> machine: disable serial flow control settings when not applicable

plover/oslayer/xkeyboardcontrol.py
* some cleanups: fix identifiers of private class/object members
* factorize the X11 event loop code so it can be reused
=> xkeyboardcontrol changes

archlinux/PKGBUILD, rpm/package.spec
=> Fix Arch Linux & Fedora Rawhide packages dependencies

plover/oslayer/config.py
=> oslayer/config: fix portable mode handling on macOS

plover/formatting.py, test/test_blackbox.py
=> formatting: fix handling of replaced text

plover_build_utils/install_wheels.py, setup.py
Ensure Python calls are isolated from the development environment. Fix #992.
=> windows: fix distribution build

plover/config.py, plover/dist_main.py, plover/system/__init__.py
* fix distribution launcher
* fix deprecation warnings
=> Fix Python 3.7 support

plover_build_utils/get_pip.py
=> utils: update checksum for pip 19.0.1

plover_build_utils/testing.py, test/test_default_dict.py
This also add a dedicated test to check for invalid entries.
=> Fix invalid dictionaries entries

plover_build_utils/get_pip.py
=> utils: pin get-pip to pip 19.0.2

linux/appimage/build.sh
The `get_desktopintegration` helper has been removed.
=> linux/appimage: fix creation

plover/gui_qt/config_window.py, plover/gui_qt/main_window.py, plover/gui_qt/main_window.ui
Don't configure the machine used from a translated machine name.
=> Fix machine type i18n support

linux/appimage/build.sh, plover_build_utils/functions.sh, plover_build_utils/get_pip.py, requirements.txt, requirements_base_devel.txt, requirements_distribution.txt, requirements_plugins.txt
Improve builds reproducibility and avoid breakage with pip 20.3.
Closes #1177.
=> pin pip's version

setup.cfg
Reached end of life September 5, 2020.
=> setup: drop Python 3.5 support

setup.cfg
Fix warning when checking the source distribution with `twine check`.
=> setup: minor metadata cleanup

news.d/bugfix/1159.core.md, plover/steno.py, plover/system/__init__.py, test/test_blackbox.py
Fix an issue with implicit hyphen handling with some theories (like Melani).
=> steno: fix stroke implicit hyphen handling

setup.py
Same issue as with `dist_main.main`.
=> setup: fix `launch` command on Windows

news.d/feature/1165.ui.md, plover/gui_qt/messages/es/LC_MESSAGES/plover.po
=> Add translation into Spanish

README.md
Limit status/link to the master branch.
=> readme: tweak CI badge

plover/gui_qt/config_window.ui, plover/gui_qt/main_window.ui, plover/gui_qt/suggestions_dialog.ui
Remove some unused slots from UI files.
=> gui_qt: minor cleanups

plover_build_utils/functions.sh, plover_build_utils/get_pip.py, reqs/bootstrap.txt, reqs/constraints.txt
Pip's new resolver is too buggy.
=> Pin pip back to 20.0.2

linux/appimage/build.sh, osx/make_app.sh, windows/dist_build.sh
Work around https://github.com/pypa/pip/issues/9781.
=> fix distributions' PEP 517 support

news.d/feature/1092.core.md, news.d/feature/1212.core.md
=> news: add missing fragments.

news.d/feature/1264.ui.md, plover/messages/nl/LC_MESSAGES/plover.po
I noticed that there are GUI translations in Plover, so I went ahead and made a Dutch translation:
=> Add Dutch UI translation

plover/messages/es/LC_MESSAGES/plover.po
Updated translation into Spanish.
=> Update translation into Spanish

news.d/feature/1268.ui.md, plover/messages/it/LC_MESSAGES/plover.po
Thanks to @Sillabix for the translation.
=> add Italian translation

.gitignore, news.d/bugfix/1271.osx.md, osx/app_resources/dist_blacklist.txt, osx/make_app.sh, plover/oslayer/log_osx.py
- Extract the Python binary from the bundled Python.app
- Unsign it so that our custom PList is respected
Closes #1237
=> osx: Fix notifications not showing as from Plover

plover/oslayer/winkeyboardcontrol.py
=> oslayer/winkeyboardcontrol: remove duplicate imports

plover/system/__init__.py
This *should* finish everything I wanted to do with the orthography wordlist. The assertion will ensure no duplicate words exist in the built-in wordlist and will also end up catching any custom lists that were based on the previous version (which had around 1500 duplicates, some with incorrect rankings for distressingly common words). This allows the elimination of a sort, and arranging the other code to minimize Python interpreter overhead makes the wordlist load *much* faster:
Before
```
ncalls   tottime   cumtime  filename:lineno(function)
1     0.000     0.568  system\__init__.py:12(_load_wordlist)
1     0.112     0.393  system\__init__.py:26(<listcomp>)
338882     0.251     0.251  {method 'rsplit' of 'str' objects}
1     0.040     0.090  {method 'sort' of 'list' objects}
1     0.085 …
```
=> Optimize wordlist loading

reqs/bootstrap.txt, reqs/ci.txt, reqs/constraints.txt, tox.ini
* add requirements for generating CI workflow
* add missing `PyQt5-Qt5` to constraints
=> Tweak requirements

plover_build_utils/pyqt.py
* improve comments:
```diff
-# i18n: Widget: “AboutDialog”, windowtitle.
+# i18n: Widget: “AboutDialog”, window title.
```
* fix corner case
=> improve gettext hook

news.d/feature/1306.core.md, plover/dist_main.py, plover/gui_qt/engine.py, plover/gui_qt/main_window.py, plover/gui_qt/trayicon.py, plover/i18n.py, plover/log.py, plover/macro/undo.py, plover/main.py, plover/oslayer/config.py, plover/oslayer/keyboardcontrol.py, plover/oslayer/log_plyer.py, plover/oslayer/processlock.py, plover/oslayer/wmctrl.py, reqs/constraints.txt, reqs/dist.txt, setup.cfg, test/test_config.py, test/test_misc.py, test/test_translation.py
Add FreeBSD/OpenBSD support.
Closes #931.
=> add FreeBSD/OpenBSD support

news.d/bugfix/1314.ui.md, plover/gui_qt/main_window.py
Correctly restore the window if it was minimized.
=> fix restoring main/tool window

news.d/api/1284.break.md
=> add missing news entry

plover/formatting.py, plover/machine/base.py, plover/translation.py
Minor change. Closes #1272.
I'm not really good at writing docstrings, just put the PR here.
=> Fix several mistakes in docstring

reqs/constraints.txt
=> fix Linux build

news.d/bugfix/1388.core.md, plover/engine.py
Closes https://github.com/openstenoproject/plover/issues/1381 .
*(is the approach okay? I don't think there's any other instance in Plover code that the filter feature is used)*
=> Do not remove filters on dictionaries reload

plover/gui_qt/dictionaries_widget.py, plover/gui_qt/dictionaries_widget.ui, plover/messages/plover.pot
Rename "open dictionaries" to "load dictionaries", and "new dictionary" to "create dictionary"
I could not find a specific GitHub issue for this, but some people have been struggling to understand which button to press to use their existing dictionaries when coming from non-Plover software. It was suggested that changing the wording might help with this (discord links [here](https://discord.com/channels/136953735426473984/136953809409802240/925834811094990968) and [here](https://discord.com/channels/136953735426473984/850891109140004864/934828102859767879). scroll up for context). Feedback on exact wording is appreciated.
---
I haven't worked with i18n code before, so please let me know if there is a better way to do it than I did.
- There were several `msgid`s:  "&add dictionaries" for …
=> Rename "add dictionaries" options

news.d/feature/1498.linux.md, plover/gui_qt/main.py
Fix missing `WM_CLASS` window property on Linux.
Closes #1497.
=> gui_qt/main: set application name

windows/dist_build.sh
Build/cache the wheels we need first using the default Python, so C extensions can be successfully built (the embedded distribution does not include the necessary files, e.g. `Python.h`).
=> windows: improve distribution build script

news.d/bugfix/1512.core.md, plover/steno_dictionary.py, test/test_steno_dictionary.py
=> steno_dictionary: fix `StenoDictionaryCollection.longest_key`

news.d/bugfix/1274.windows.md, plover/oslayer/windows/keyboardcontrol.py
(title)
Closes #1154 . See the issue for more info.
=> Remove extended keys flag on Windows

plover_build_utils/get_pip.py
To match the version in `reqs/constraints.txt`.
=> utils/get_pip: update to 21.3.1

.github/workflows/ci.yml, .github/workflows/ci/workflow_context.yml, doc/developer_guide.md, news.d/api/1538.break.md, plover/engine.py, setup.cfg
Reached end-of-life six months ago (23 Dec 2021).
=> drop support for Python 3.6

news.d/bugfix/1599.windows.md, plover/gui_qt/dictionaries_widget.py
Normalized filepath name to fix bug with windows tests
=> Fix Windows Tests

plover/gui_qt/dictionaries_widget.py
=> Re-enable drag-drop of items

plover/messages/zh_tw/LC_MESSAGES/plover.po
Added Traditional Chinese Translation to Plover's language list.
Closes
=> Added Traditional Chinese Translation

README.md
Updates URLs for wiki and icons in readme. No code changes.
=> Update old URLs in readme

.github/workflows/ci.yml, .github/workflows/ci/helpers.sh, .github/workflows/ci/workflow_template.yml, .gitignore, doc/ci.md, pyproject.toml
Removes the logic that generates continuous GitHub releases. See [this discussion](https://discord.com/channels/136953735426473984/144999734254370816/1361076524278747136) on Discord.
=> Remove continuous release logic

.github/workflows/ci.yml, .github/workflows/ci/workflow_template.yml, doc/plugin-dev/gui_tools.md, news.d/feature/1735.core.md, plover/plugins_manager/__main__.py, plover_build_utils/setup.py, setup.py
Integrate BuildResources into BuildUi so that existing UI plugins don't need to change their setup.py.
Closes
=> Integrate BuildResources into BuildUi

linux/appimage/blacklist.txt, news.d/feature/1741.core.md, osx/app_resources/dist_blacklist.txt, plover/gui_qt/about_dialog.py, windows/dist_blacklist.txt
Reduces the plover installer file size by updating the blacklist files for PySide6.
Closes #1736
=> Reduce installer file size by extending file blacklists

doc/plugin-dev/setup.md
Updates the versions in the plugin setup documentation plus some hints
Closes #1696
=> Update versions in plugin setup documentation

index.html
-updated links which directed to the github wiki and not to the new one at plover.wiki
-changed one alt in the HTML as it mentioned github
=> Update URL's in index.html
