- plover/gui/keyboard_config.py
- plover/machine/keymap.py
- plover/machine/sidewinder.py
A keymap is used as a dictionary from an input key (say "q") on a
regular keyboard to a steno key (such as "S-").  Since there may be more
than one key on a keyboard mapped to a single steno key, the dictinary
is generated from a list of steno keys mapped to a list of keyboard
keys.  The keymap is stored in the configuration file as a JSON array.
An ordered dictionary is used for display purposes only, i.e. to list
the key assignments in the same order in the configuration dialogue.
This feature can be used by Dvorak typists who do not normally use a
QWERTY layout, or those with keyboards featuring unusual key positions.
> replace fixed key mapping with customisable keymap

- plover/assets/dict_unsorted.json
This adds to the already existing but overly specific "a pedometer".
> Add "pedometer" to dictionary

- plover/formatting.py
Addresses #216 by encoding into UTF-32 before calculating common prefix,then decoding back to Unicode for output through the OS layer.
It works because UTF-32 is fixed-width, so each character always takes 4 "lengths". That's why when we get common prefix, I divide then multiply by 4. That rounds the result to get you the right count. I've tested against the issues I mentioned in the issue.
> Fix counting and output of long Unicode characters

- plover/oslayer/winkeyboardcontrol.py
This pull request contains two commits.
The first is a simplification and correction, whereby meta keys are monitored as a group, rather than individually (since no behavior is determined based on the particular key in question), and also now their down state is properly monitored. See commit message for details.
The second commit adds Windows key commands to the list of actions that will act as usual and be ignored by plover.
> Allow Windows keys behavior, and other passthrough keys enhancements.

- plover/gui/add_translation.py
- plover/gui/lookup.py
- plover/gui/util.py
It looks like when the LOOKUP feature was added and O/S-specific utilities were refactored out into plover.gui.util, the Linux version of SetTopApp was still using the TITLE global (now defined in both lookup.py and add_translation_py).
Modified the SetTopApp function in plover.gui.util to require a dialog object, confirms it has rendered, and passes the title to wmctrl to bring it to front. Also modified plover.gui.lookup and plover.gui.add_translation
to accommodate the util change.
For the problem of returning focus, it seems as though calling Destroy() on a child window returns focus to the parent. The original on_close handlers called SetForegroundWindow before Destroy. Reversed that order, and it also seemed to require a call to Update after Destroy to make sure the dialog has …
> Linux: fix SetTopApp crash

- plover/oslayer/xkeyboardcontrol.py
Support 3rd (AltGr) layer.
Not as good as full Unicode support, but at least when using an "international" keymap variant (e.g. `setxkbmap us -variant intl`) all those AltGr+key combinations will be supported.
> oslayer: improve xkeyboardcontrol handling of layout

- plover/steno.py
- plover/test_steno.py
Interpret number strokes so that an entry like 18 gets read as 1-8. I don't think that users should have to think about explicit dashes when dealing with numeric entries.
Additionally, this change makes it so that the Plover add translation dialogue correctly inserts "1-8" into the dictionary. The regex string for this kind of stroke is [1-4][6-9]. That means that numbers on opposite sides of the keyboard in the middle this stroke effectively count as an implicit asterisk.
The only issue I can think of would be that the user could have duplicate strokes in their dictionary if they have both "19" and "1-9" defined, for example. But is that a big enough issue compared to not being able to define strokes with numbers in them? I don't think it is, but you, the reviewer, can weigh in.
> Better normalize number strokes to insert dash, fixes #276

- plover/app.py
- plover/log.py
Show a warning and rename the file to `"strokes.log"`, updating and saving the configuration.
> log: automatically rename strokes log on conflict

- plover/gui/log.py
- plover/gui/log_osx.py
Use Notification Center if available on Mac.
Instead of the wx notifications, which are pretty awful looking on OSX, I changed to notification center, which acts like other applications. The biggest limitation is that we can't expire notifications, but OSX users should be used to that. Here is the hover view and the history view for the notification:
> Add Mac Notification Center support

- plover/machine/stentura.py
- plover/machine/test_stentura.py
Fix the tests that got broken with the recent changes to timeout handling.
I don't have a Stentura, but only added some sanity check to the read code, so hopefully it still works with a real machine.
> Fix stentura tests

- plover/app.py
- plover/gui/keyboard_config.py
- plover/gui/main.py
- plover/machine/base.py
- plover/machine/sidewinder.py
- plover/oslayer/osxkeyboardcontrol.py
- plover/oslayer/winkeyboardcontrol.py
- plover/oslayer/xkeyboardcontrol.py
Cleanup the keyboard machine code, now that all `KeyboardCapture` implementations support suppression (which also mean we can get rid of the dependency on `KeyboadEmulation`).
Rework the way machines handle suppression to:
- avoid the need for testing for a particular class instance to know if suppression is needed
- suppress all the key down events when post-suppressing a stroke: previously, when toggling Plover on with a stroke, key auto-repeat events were not suppressed (those can happen when being a little heavy handed and/or configuring X11 with a low delay for triggering auto-repeating)
Also change the `KeyboardCapture` implementation so list of suppressed keys is not set once and for all at initialization, which will make it easier to share capture instances (e.g. in the keyboard …
> Rework keyboard suppression

- osx/README.md
Frustrated with having to build Plover between code changes, I finally took the time to figure it out. @jeremy-w, you pay be interested in this change.
> Add command to run Plover in development on OS X

- plover/machine/treal.py
The Tréal file was set to use non-blocking reads from the hidapi. But that code was in a while loop, and so it was called infinitely, causing very high CPU usage. I've switched over to a blocking version of the call, which actually gives Plover a break in the while loop.
The effects have only been positive so far. I feel a little silly for not noticing this high CPU usage before in the months using Plover with the Tréal 😕
> Reduce Tréal CPU usage

- plover/oslayer/keyboardcontrol.py
Updated in wake of #341.
The code run when running the module directly was still trying to pass suppressed keys to the `KeyboardControl` initializer, which led to a "you gave me 2 args but I only take 1" error. It also tried to turn suppression on, except that API now takes a set of keys to suppress, so that bombed out griping that Bools are not iterable.
> Fix keyboardcontrol script

- .gitignore
- appveyor.yml
- plover/test_config.py
- plover/test_log.py
- setup.py
- windows/helper.py
- windows/hook-plover.py
The Appveyor build consist of the following steps:
-  install all the required packages
-  run the testsuite
- package a version with PyInstaller.
The version number will be derived from `git describe --tag`, e.g. `v2.5.8-301-g6284391` -> `Plover-2.5.8+302.g315e5ee.exe`.
Most of the work is done by the `windows/helper.py` script, which can also be used on Linux to setup a Wine prefix to test and package the Windows version (see `--help` for usage).
> Add Appveyor support

- .gitignore
- osx/README.md
- osx/makefile
- plover/oslayer/osxkeyboardcontrol.py
We were using 32-bit builds due to an old version of wxPython.
Additionally, PyObjc had an update that allowed us to use
"CGEventKeyboardSetUnicodeString" without a conversion through
PyObjc.
The application could still technically be built with 32-bit
support in "universal" fashion, but that value is super marginal,
because it's more complex to get setup and this would only affect
users on 32-bit OSX machines, which are very few. If they insist
on 32-bit, they can use the older builds.
The other reason to stick with a stripped application is the
filesize. A universal OSX application weighs in at about 90MB,
the 64/32-bit-only versions are a lighter 50MB (less in a .dmg).
@jeremy-w Can you please try this out and see if it resolves your
issues with Plover crashing after running it as …
> Switch to x64 builds on Mac

- doc/plover_guide.md
This was just an automatic conversion via
`pandoc -f latex -t markdown plover_guide.tex -o plover_guide.md`,
but it appears to have got the job done.
[#261]
> Add Markdown version of Plover Guide

- osx/README.md
- osx/bootstrap.sh
- osx/requirements.txt
- Replace manual instructions to `pip install` a list of packages with requirements.txt
- Replace manual setup instructions with a bootstrap script
- Rewrite the README to point people at the bootstrap script first and supply additional information as a "For the More Curious" section.
The largest change in the README is to discourage people from using a virtual environment for developing Plover. It ends up not being all that virtual in the end anyway thanks to wxPython.
This is an improvement, but it's not sufficent; I still don't have a functional dev environment myself. I can build an app bundle, but it fails during launch. Running from the commandline with `arch -32 /usr/local/bin/python -m plover.app` runs afoul of the `objc` package not having a 32-bit slice.
32-bit apps under OS X …
> Simplify OS X dev setup

- osx/bootstrap.sh
Trying to check architecture made it needlessly brittle.
Of course it's going to be 64-bit, if it works at all.
> osx/bootstrap.sh: Check presence, not architecture

- plover/gui/add_translation.py
The event handlers weren't terminating properly, caused an issue Windows where the cursor wasn't present on Windows. Seems fine on OSX, too. @benoit-pierre, can you try Linux?
> Add cursor to Add Translation Dialog on Windows, fix #309

- plover/log.py
Otherwise, it acts as a second (possibly more restrictive) filter, after
the logger level. Leaving it unset make it possible to change the level
at the logger level.
> log: don't set the print handler level

- plover/formatting.py
- plover/test_formatting.py
This pull adds several different cases. Namely:
- CAPITAL CASE
- Title Case
- lower case
- snake_case
- CamelCase
They are controlled by "MODE" commands, similar to "PLOVER" commands. They can be toggled with CAPS, TITLE, LOWER, SNAKE, and CAMEL. They can all be turned off with CLEAR.
CAPS, Title case, and lower case are mutually exclusive, so turning on one will turn off the others. CamelCase is mutually exclusive to all other cases. Snake case is only exclusive with camel case.
This means CAPS, title, and lower case can be used with snake case. This functionality is useful for programmers and regular stenographers alike. The cases are useful for programmers while coding, such as in variable names. For regular stenographers, CAPS can represent yelling, or scene cues, for example. Title …
> Add different output modes: Caps, Title, Lowercase, Snake, Camel

- plover/config.py
- plover/machine/keyboard.py
- plover/machine/registry.py
- plover/machine/test_registry.py
In the code, we still refer to the Sidewinder even though it is no longer relevant for most users. As such, it's a little confusing when you are looking for the "keyboard" machine and you need to learn that it's called the Sidewinder internally. Also, it's a little misleading to say "NKRO Keyboard: connected", because users who don't have an NKRO keyboard will open Plover and see this message, and may be confused.
These issues affected me when I very first started using Plover (no NKRO keyboard, looking to find the plover/machine/keyboard).
@stenoknight, can I get your comment on this? Particularly, the change from "NKRO Keyboard: connected" to "Keyboard: connected"?
> Rename "NKRO Keyboard" and "Sidewinder" to "Keyboard"

- plover/gui/config.py
- plover/gui/main.py
- plover/gui/serial_config.py
Fixes visual appearance of too-wide triple-dot.
Required setting a coding through a
[magic comment](https://www.python.org/dev/peps/pep-0263/)
in order to avoid ugly raw Unicode escapes.
> Replace triple-dot with ellipsis in user strings

- plover/oslayer/osxkeyboardcontrol.py
We switched over to the PyObjc version of set Unicode string when going to 64-bit, and this broke a work around that [Hesky had figured out](http://stackoverflow.com/questions/18027342/how-can-i-call-cgeventkeyboardsetunicodestring-from-python) a while back. With the current dependencies, we don't need the work around.
In master right now, emojis crash output, this change fixes that.
Tested on Mac.
> Fix a Mac crash relating to long Unicode after switching to 64-bit

- plover/oslayer/winkeyboardcontrol.py
- setup.py
- windows/README.md
- windows/helper.py
The keyboard emulation through SendKeys had some issues. Namely, it was not possible to emulate Windows key or a lot of special keys. It also didn't emulate keys, rather it sent characters to the foreground application.
I have rewritten the emulation using SendInput, which is a little more low-level. It can emulate most keys on the OS level, and it uses CTypes. It also has support for outputting Unicode characters using VK_PACKET. For more information, the commit messages have details surrounded around the various commits.
> Rewrite keyboard emulation for Windows

- plover/oslayer/xkeyboardcontrol.py
This is done by dynamically changing the keymap when a character we want
to send is not already mapped. A rolling list of unused keycodes is used
to ensure we don't reuse a keycode before the target application has
time to process each sequence of keymap change + key press/release
events. The keymap entries used by Plover are marked with a special
keysym, so if Plover is killed/restarted, those entries are still
considered unused, and consequently reusable.
> oslayer/xkeyboardcontrol: add Unicode support

- .travis.yml
Add a Travis build for OSX on Travis.
Travis doesn't support Python on OS X, so we need to use generic language.
The commands install the Python we need, then get wx, then run the
bootstrap.sh for the OSX setup to make sure everything is good and get pip
dependencies. The deployment will publish builds to GitHub tags, but
otherwise will just discard the build. Maybe later we can add another
deployment for non-tagged builds.
> Add OS X Travis build

- plover/gui/add_translation.py
Prevent another Unicode-caused crash with the shorten Unicode function on Mac:
Only tested on Mac.
> Shorten unicode on Add Translation dialog

- .travis.yml
- appveyor.yml
- launch.py
- setup.py
- windows/helper.py
* add Linux to the build matrix
* run test suite for both OSX and Linux builds
* add egg and wheel deployments to the Linux build
* reduce overlap in dependencies handling when possible by using `setup.py develop` to install those that are supported by pip
> Add Linux support to Travis CI

- plover/gui/add_translation.py
- plover/gui/config.py
- plover/gui/keyboard_config.py
- plover/gui/lookup.py
- Default label for Cancel labels is '&Cancel', meaning any time
the user tries to copy on OSX (Cmd-C), the active window would
"cancel".
- See wx bug: http://trac.wxwidgets.org/ticket/15678
> Override Cancel labels, fix #373

- plover/formatting.py
- plover/test_formatting.py
When trying to currency format after an output that wasn't a number, there
was an exception and Plover's output would cease completely.
To work around this is just to define the case where the user's previous
word is not a number, at which point the command should do nothing.
Explicitly added tests for the 0 cases as well, because they are edge.
> Fix currency retroformatting exception

- plover/gui/main.py
By removing the Layout() call, the spinner gets placed incorrectly on initialize.
I've only tried Mac so far.
> gui/main: fix spinner placement

- plover/test_translation.py
- plover/translation.py
Don't add those strokes to the state history (since undo strokes are not supposed to be undo-able).
> translation: fix undo strokes on empty state

- .gitignore
- plover/oslayer/mac_keycode.py
- plover/oslayer/osxkeyboardcontrol.py
Change `osxkeyboardcontrol.py` to use key codes based on the user's current layout, instead of just setting the string and sending key code 0. I imported `mac_layout.py`, a creation from @willwade where he used the base code in `PyKeycode` for the purpose of porting over functionality to `PyUserInput`. Because that code is not published, I had to copy and add attribution instead of some clever `import`. The new OSX `send_string` also tries to group modifier presses to avoid to avoid unnecessary key presses, as would be in the case of sending in all CAPS output.
Fixes #246, which in turn has a couple of results for a typical Mac user. I've noticed the keycodes to be helpful in the following specific cases:
- Plover no longer crashes when it emulates keypresses onto itself
- Anki accepts …
> OSX: Send key codes instead of strings when possible

- plover/oslayer/xkeyboardcontrol.py
Fix #387:  in this instance`Super_L` is also mapped to a higher keycode with a modifier, and this end-up as the default mapping in our keymap. The problem is `send_key_combinations` expect mappings with no modifiers, and ignore them.
The solution is to prefer lower modifiers combos when building the mapping table.
> Fix xkeyboardcontrol send_key_combination

- plover/app.py
- plover/config.py
- plover/formatting.py
- plover/gui/config.py
- plover/test_formatting.py
Add output configuration options so that the first stroke after Plover is enabled can be capitalized or attached (no space). The default behavior is the same as Plover 2.5.8, and this shows up as checkboxes in the output section of the configuration.
This never really bothered me until @stanographer asked for it. It seems like a sensible feature, because some users (like me) always want no space and capitals, some users might want capitals *with* a space (writing text, for example), and some users may not want this change at all.
Configure whether Plover's first stroke after being turned on is capitalized and has a space.
Only tried on OS X, but also included test cases to verify the functionality.
> config: allow first stroke to be capitalized and attached

- plover/config.py
- plover/gui/add_translation.py
- plover/gui/config.py
This is a continuation of #252, rebased against master.
It has been reworked to set alpha/opacity rather than transparency, so that 100% means fully opaque not fully invisible.
- Done. <img width="603" alt="captura de pantalla 2016-02-24 a las 16 52 23" src="https://cloud.githubusercontent.com/assets/29010/13302752/8c535404-db19-11e5-95bf-09d3f6604656.png">
- User-fixable: Minimize the window.
> Add Translation Transparency

- plover/config.py
When the configuration is stored in a mapped UNC path on Windows, e.g.
"Z:\", the path returned by `os.realpath` will already ends with "\".
> config: fix handling of relative paths

- plover/gui/config.py
Call "Layout()" to prevent artifacts. Seems like an innocent regression while refactoring.
Fixes #391
Windows 10 and OS X El Capitan tested, @benoit-pierre if you could verify that this didn't regress your Linux, then please merge
> Fix #391 - Remove artifacts from Windows config dialog

- plover/__init__.py
Update contributors dialog with a link to GitHub to reflect the many developers that we are lucky to have. Also reword to better highlight @stenoknight as the founder of the project.
- Include a non-clickable link to the GitHub repo
- Reformat to ensure that the about window doesn't resize when expanding and collapsing sections.
Fixes #372
Only tested OS X, I believe this window type is supposed to be cross platform (GTK-style about dialog)
> Update contributors in about dialog

- plover/app.py
- plover/config.py
- plover/gui/keyboard_config.py
- plover/gui/paper_tape.py
- plover/gui/suggestions.py
- plover/machine/base.py
- plover/machine/geminipr.py
- plover/machine/keyboard.py
- plover/machine/keymap.py
- plover/machine/passport.py
- plover/machine/stentura.py
- plover/machine/test_passport.py
- plover/machine/treal.py
- plover/machine/txbolt.py
- plover/oslayer/keyboardcontrol.py
- plover/steno.py
- plover/system/__init__.py
- plover/system/english_stenotype.py
Move all system/theory related parameters to a dedicated module:
* steno keys, number keys, suffix keys
* undo stroke
* orthography word list and rules
* default keymaps for supported machines
Note:
* the keyboard keymap configuration option was moved out of the `[Keyboard]` section to a new `[System: English Stenotype]` section
* although not supported in the GUI, it was simpler and cleaner to use a generic approach, so it possible to change a machine (other than the keyboard) keymap through the configuration, e.g.:
```python
[System: English Stenotype]
keymap[treal] = [["#", ["#1", "#2", "#3", "#4", "#5", "#6", "#7", "#8", "#9", "#A", "#B", "X3"]], ["S-", ["S1-", "S2-"]], ["T-", ["T-"]], ["K-", ["K-"]], ["P-", ["P-"]], ["W-", ["W-"]], ["H-", ["H-"]], ["R-", ["R-"]], ["A-", ["A-"]], …
```
> Add preliminary system support

- plover/app.py
- plover/gui/config.py
- plover/gui/log_dbus.py
- plover/gui/log_osx.py
- plover/gui/log_wx.py
- plover/gui/main.py
- plover/log.py
- plover/machine/keyboard.py
Fix #273.
* use blanket except clauses so Plover does not crash if something goes wrong during the init.
* use the logger for reporting exceptions.
* use a custom formatter for GUI log handlers: don't show traceback on exception, since the messages are usually limited in length, and the information is not really useful to most users (the full traceback is still logged to the console and the logfile).
> More robust init

- plover/app.py
- plover/config.py
- plover/gui/config.py
- plover/gui/suggestions.py
Add buffer configuration, default 100. UI arbitrarily maxes out at 100,000, minimum is set to 1.
Fix #300
> Add stroke buffer configuration, default to 100

- plover/app.py
For consistency with the rest of the engine code, don't use the configuration. (This was previously done because of the multiple calls to `engine.set_stroke_filename`)
> app: change engine.set_stroke_filename

- .travis.yml
- appveyor.yml
- setup.py
The constraints:
* Travis CI deploy on tag
* when creating a draft release with AppVeyor, the tag creation is deferred to publication, so Travis CI (deployment) builds won't start until the release is published
* it's better to create a draft release, so we get a chance to edit release notes, and test the build artifacts before the actual release
So this pull request change the process of creating a new weekly to:
* run: `./setup.py tag_weekly`, this will tag the current `HEAD` based on the last stable release, e.g. `weekly-v2.5.8+443.gf47e969`
* push the tag to GitHub (the branch does not matter)
* AppVeyor and Travis CI will both start buildings, and their artifacts will be deployed to a draft release
* edit the draft release notes, test the build artifacts
* publish!
Note:
* the …
> Rework AppVeyor and Travis CI deployments

- setup.py
Unfortunately, our egg and wheel files for the first weekly don't work because of this missing module...
> setup: add missing 'system' module to packages

- plover/formatting.py
- plover/test_formatting.py
Lower meta doesn't have text content, so "was_space" wasn't triggering for the next action. Workaround is to replace space and set lower's text to space, in order to carry over the "was_space" state.
Fixes #407 
Fix fingerspelling when output is set to place spaces after.
> Lower meta: carry space to maintain was_space state

- plover/formatting.py
- plover/test_formatting.py
- plover/test_translation.py
- plover/translation.py
Retro-del-space would only join the previous two translations, which didn't work for cases like "{.}" because the output would be "{.}word" which equates to ". Word". Instead, now we join with `{^~|^}` which will remove the space and maintain capitalization (".Word" in this example).
Also handle numbers. Previously we only used the translation's english value, but if the stroke is a number it has no english value.
Fixes #402, #405
Fix retroactive delete space with punctuation, numbers, and other meta commands.
> Fix retro delete space to work with meta actions and numbers

- plover/oslayer/osxkeyboardcontrol.py
Explicitly remove mask flags that we *don't* want, if they are not properly set. This extends the already present functionality. The results is that complex strings like `>µ>µ>µ>µ` work, where before they would come out as `≥Â˘Â˘Â˘Â˘µ>` or similar.
The change to HIDSystemEvent also fixes this case in KDiff3 and other legacy applications.
Also add a delay to output when sending key sequences, may fix the transposition issue.
> osxkeyboardcontrol: explicity remove unwanted mask flags

- plover/app.py
Of course this was working when testing switching machines between `Keyboard` and `Treal`...
> app: fix embarrassing typos in update_engine

- plover/log.py
- plover/main.py
* add thread name to default log formatter
* add command line switch to change log level
Note: the default level has been reduced from *INFO* to *WARNING*.
> Improve logging

- plover/machine/registry.py
- plover/machine/treal.py
- setup.py
- windows/helper.py
- Add Treal reconnect, which starts after losing the connection.
- Try to connect to all 10 Treal devices, which can be switched using a switch on the bottom of the machine.
- Change to hidapi on Windows in order to unify modules cross platform.
Tested on OS X and Windows (used AppVeyor builds)
> treal: automatically reconnect

- windows/README.md
- windows/helper.py
We do need Cython and VS for Python installed when using `setup.bat` to setup a dev environment.
> Fix Windows dev env automatic setup and update instructions for manual procedure

- plover/gui/main.py
Output from the machine thread, this fix an issue with modal dialogs not receiving output on Mac OSX.
Tested on Linux and Windows 10 VM.
> gui/main: don't defer output to the GUI thread

- osx/makefile
Remove unused duplicate copy of assets directory:
```shell
> ls Plover.app/Contents/Resources/
american_english_words.txt  __error__.sh  plover.ico       site.pyc
__boot__.py                 include/      plover-icon.svg  spinner.gif
commands.json               launch.py     plover.png       up.png
connected.png               lib/          refresh.png      user.json
disconnected.png            main.json     remove.png
down.png                    plover.icns   share/
> unzip -l Plover.app/Contents/Resources/lib/python2.7/site-packages.zip 'plover/assets/*'
Archive:  Plover.app/Contents/Resources/lib/python2.7/site-packages.zip
Length      Date    Time    Name
---------  ---------- -----   ----
0  2016-03-12 18:26   plover/assets/
4491762  2016-03-12 18:18 …
```
> osx: optimize dmg size

- .travis.yml
Needed so `git describe --tags` output is consistent (only fetching down to the last accessible tag is not enough).
> travis: unshallow clone

- plover/oslayer/winkeyboardcontrol.py
- plover/oslayer/xkeyboardcontrol.py
Add support for media keys on Linux. Both 'XF86_AudioMute' and 'AudioMute' are supported.
> oslayer/xkeyboardcontrol: add support for media keys

- plover/oslayer/mac_keycode.py
Adjust a broken control block in `mac_keycode`. This was exposed when layout was set to US: Extended / ABC: Extended.
Fixes #432
Tested on OS X El Capitan.
> Fix crash while loading Mac key layout

- .travis.yml
- linux/README.md
- osx/makefile
- plover/oslayer/config.py
- setup.py
- utils/metadata.py
- windows/helper.py
- windows/hook-plover.py
Add the required packages metadata so `pkg_resources` can be used.
Tested with a Windows 10 VM.
> Fix Windows and Mac distributions so pkg_resources can be used

- plover/gui/add_translation.py
If I had Plover set to start capitalized, the first stroke when writing into the "Translation" field of the "Add Translation" dialogue would be capitalized. That's unexpected... instead I've set it to simply suppress the space, which I think is a fair default state for that field.
> Add default state to Add Translation dialog

- plover/oslayer/osxkeyboardcontrol.py
- plover/oslayer/winkeyboardcontrol.py
Add OSX media keys. Supported keys (x names):
```python
"AudioRaiseVolume": 0,
"AudioLowerVolume": 1,
"MonBrightnessUp": 2,
"MonBrightnessDown": 3,
"AudioMute": 7,
"Num_Lock": 10,
"Eject": 14,
"AudioPause": 16,
"AudioPlay": 16,
"AudioNext": 17,
"AudioPrev": 18,
"AudioRewind": 20,
```
I didn't include keyboard brightness up, down, and toggle. There doesn't seem to be an XF86 equivalent, and I'm not sure what the value of controlling keyboard brightness from the steno machine would be.
Also added the Fn modifier, but it's not exactly expected behavior because it is an external keyboard--the top-row equivalent of the Mac laptop keyboards won't occur.
> OSX: Add special media keys, extend Windows' Media Keys

- plover/dictionary_editor_store.py
- plover/gui/add_translation.py
- plover/gui/dictionary_editor.py
- plover/steno_dictionary.py
2 sets of changes:
* changes that I think should be part of the next release:
- fix call to `util.SetTopApp`
- change steno dictionary save API, so the dictionary editor can be made to only save back those dictionaries that have been modified (instead of always saving **all** dictionaries)
* preliminary changes for multilingual/plugins support (if deemed too risky, I'll rewrite the PR to remove those, and defer them after the release):
- don't uppercase strokes in the add translation dialog or dictionary editor: some systems use lower case letters too (e.g. Italian)
- better handle *read-only* dictionaries, i.e. if a dictionary's `save` field is `None`; this will be needed for proper support of Python dictionaries and dictionaries loaded directly from assets
> a few dictionary related changes

- plover/machine/base.py
Should be a string, or split will not be happy...
> machine/base: fix default KEYS_LAYOUT

- plover/gui/main.py
Turns out outputting from the machine thread doesn't work with bulk sending of key codes.
Fixes #444 
This reverts commit 03a89bb62bef7834f5c696c00c326f2e83e012dc, reversing
changes made to 11d2a2fe6c5cc6dc428baf63e01d464af8ee88b6.
> Revert "output from machine thread"

- launch.bat
- launch.py
- launch.sh
- linux/README.md
- osx/README.md
- plover/main.py
- setup.py
- windows/README.md
Will make sure metadata is up-to-date before starting Plover, as running `python2 -m plover.main` without Plover installed results in an exception in `oslayer/config.py`:
```
pkg_resources.DistributionNotFound: The 'plover' distribution was not found and is required by the application
```
> setup: add 'launch' command and associated scripts

- plover/gui/main.py
- plover/oslayer/keyboardcontrol.py
- plover/oslayer/winkeyboardcontrol.py
- setup.py
- windows/main.py
This allow the use of `pythoncom.PumpWaitingMessages` without interfering with the GUI loop, and ensure the keyboard hook is run in a timely manner: no competition with other threads and captured key events are posted to queue without further processing. This fixes #454 on Windows.
Note: a custom main with a set of specific workarounds must be used for correct multi-processing support when using PyInstaller, especially with '--onefile'. See: https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing
Tested with a Windows 10 VM: the easiest way to reproduce the bug is to keep a key pressed during Plover startup.
> move the Windows keyboard capture to its own process

- linux/README.md
Add missing `libudev-dev` dependency (required for compiling `hidapi` support).
> linux: update setup documentation for Ubuntu

- plover/machine/base.py
Example: switch to TX Bolt without configuring the serial port, and you get:
```
UnboundLocalError: local variable 'e' referenced before assignment
```
> machine/base: fix traces on serial port open error

- plover/formatting.py
- test/test_formatting.py
Don't honor `replace` if it does not match at the end of the previous
text. 
This is done by providing the previous translation formatting to the `OutputHelper` class so it can render the initial text (so the matching actually be done when the first undo/to translation action uses `replace`).
This fixes #476.
> formatting: rework handling of actions 'replace'

- linux/README.md
- setup.py
- utils/metadata.py
I created some Ubuntu packages, PPA here: https://launchpad.net/~benoit.pierre/+archive/ubuntu/plover
I had to tweak `utils/metadata` and relax the version requirements for `appdirs` and `pyserial` to support Ubuntu 14.04 LTS (Trusty).
I also backported `wxpython3.0` to this PPA, and so updated `linux/README.md` to use it, this way only one extra PPA needs to be configured.
> Ubuntu related tweaks

- plover/dictionary_editor_store.py
Normalize stroke filter before filtering, so for example "RA-E" matches "RAE".
> gui/dictionary_editor: improve stroke filtering

- plover/dictionary_editor_store.py
- plover/gui/add_translation.py
- plover/gui/lookup.py
- plover/oslayer/mac_keycode.py
- plover/oslayer/xkeyboardcontrol.py
- plover/translation.py
- test/test_translation.py
It turns out that we already support a kind of undo-able return (at least on Windows): manually editing the JSON dictionary to change "{^}{#Return}{^}{-|}" to "{^\n^}{-|}" work. It's however not possible to add such an entry through Plover's GUI, and Linux and Mac OS X don't handle those embedded \n \r \t, which is what this PR is about.
Linux and OS X respective implementations have been fixed, and two helpers have been added to the `translation` module: `escape_translation` and `unescape_translation`:
* `escape_translation` is used when displaying a translation to the user (lookup / add translation dialogs...)
* `unescape_translation` is used on the user input (add translation dialog), to get the raw translation
Note:
1. the special case: `r'\\n' -> r'\n'`, so a literal "\n" can be …
> support embedded \n \r \t in translations

- osx/makefile
- plover/__init__.py
- setup.py
- windows/helper.py
- windows/hook-plover.py
I had to change back the project name to lower case, to match the existing name used on PyPI.
Note to devs: make sure to delete `Plover.egg-info` from you tree to avoid duplicate distributions info.
> fix for PyPI release

- plover/translation.py
- test/test_translation.py
Fix #496 by just outputting raw if the translation isn't defined.
Note that this is pretty workaround worthy. Retro-delete-space won't be useful in the example given in the issue because the final TEPL won't be composable into future stroke. However, that just the nature of how RDS was implemented.
> Avoid exceptions while retro delete spacing undefined entries

- plover/oslayer/winkeyboardcontrol.py
Using "{^\n^}" was not working in dialogs, fix that.
> oslayer/winkeyboardcontrol: fix support for embedded \n \r

- plover/oslayer/winkeyboardcontrol.py
- setup.py
- windows/README.md
- windows/helper.py
This was originally done to make Python 3 support easier (no official Python 3 builds for PyHook), but turn out it also fixes #477, so...
Tested with a Windows 10 VM.
> oslayer/winkeyboardcontrol: don't use pyHook anymore

- windows/helper.py
* don't manually keep track of installed packages:
- this custom list can become out-of-date with the real system state
- most packages are installed by pip, who already keeps track of this
* prevent popup dialogs during Wine prefix initialization
> windows/helper: small tweaks

- test/test_config.py
- test/test_default_dict.py
- test/test_formatting.py
- test/test_json_dict.py
- test/test_loading_manager.py
- test/test_log.py
- test/test_orthography.py
- test/test_passport.py
- test/test_registry.py
- test/test_rtfcre_dict.py
- test/test_steno.py
- test/test_steno_dictionary.py
- test/test_stentura.py
- test/test_translation.py
It's easier and better to always use the test launcher, as this will make sure the environment (path, metadata, ...) is setup correctly.
> test: remove default mains

- plover/config.py
- plover/gui/config.py
- plover/gui/main.py
Fix #475, add config to start Plover minimized.
> Add display configuration to start Plover minimized

- plover/app.py
- plover/dictionary/base.py
- plover/dictionary/json_dict.py
- plover/dictionary/loading_manager.py
- plover/dictionary/rtfcre_dict.py
- plover/steno_dictionary.py
- test/test_json_dict.py
- test/test_rtfcre_dict.py
- test/test_steno_dictionary.py
Pass a filename instead of a file like-object:
- this let each format implementation deals with the file open mode (and potentially the encoding), since it knows best.
- it allows for more powerful format implementations, e.g. a new "Python dictionary" format will want to use something like imp.load_source, as this will take care of byte-compiling the "dictionary" source code as needed.
Forward original exception traceback so the final one is actually useful when debugging.
Example when loading an bad JSON dictionary; before:
```
File "/home/bpierre/progs/src/plover/plover/dictionary/loading_manager.py", line 29, in load
raise e
DictionaryLoaderException: '/home/bpierre/progs/src/plover/invalid.json' is not valid json: Expecting property name enclosed in double quotes: line 3 column 1 …
```
> Improve dictionaries handling

- plover/gui/log_dbus.py
pynotify uses gtk, and importing gtk before wx can trigger a crash:
see http://trac.wxwidgets.org/ticket/15898
> gui/log_dbus: fix possible crash

- .travis.yml
Enable caching for pip.
Note: caching is not enabled for the Linux build, as otherwise both OS builds overwrite each other cache...
> travis: speed up the OSX build

- plover/steno.py
- test/test_steno.py
Test code:
```python
import timeit
from plover.dictionary.base import load_dictionary
def instrumented():
load_dictionary('main.json')
print '%.3fs' % timeit.timeit(instrumented, number=20)
```
On my machine (Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz), the results are:
* master: 44.549s
* this branch: 22.421s
* with `normalize_steno = lambda s: tuple(s.split('/'))`: 10.997s
> steno: optimize normalize_steno

- .travis.yml
Since Travis CI does not store artifacts, there is no point in generating them when no deployment is triggered.
> travis: speedup builds

- plover/dictionary/json_dict.py
- test/test_json_dict.py
This make it easier to externally edit such dictionaries.
> Allow non-ASCII non-control characters when saving a JSON dictionary

- .travis.yml
Now that Cython is not required at install by hidapi anymore (see [PR](https://github.com/trezor/cython-hidapi/pull/30)), the OSX build takes longer because Cython is automatically compiled by hidapi `setup.py` at installation. Speed up the build by manually installing Cython with pip (which will use a wheel if one is available, and cache the result).
> travis: speed up OSX build

- plover/gui/main.py
- plover/key_combo.py
- plover/oslayer/osxkeyboardcontrol.py
- plover/oslayer/winkeyboardcontrol.py
- plover/oslayer/winkeyboardlayout.py
- plover/oslayer/xkeyboardcontrol.py
- test/__init__.py
- test/test_key_combo.py
Factorize and simplify the handling of key combos. The syntax remains the same, but there are a few differences in the way the new implementation works:
* key names are now case insensitive, so `#{a}` is equivalent to `#{A}`, `#{Super_l(return)}` to `#{super_l(Return)}`, ...
* the goal of key combos is to support shortcuts, and key name are used instead of key codes because they are more user-friendly, as a way to indicate which physical key must be pressed / hold, so for example when using Qwerty `#{1}` and `#{exclam}` are equivalent, since both names refer to the same key (ditto for `#{Shift_L(1)}` and `#{Shift_L(exclam)}`
* a key press / hold event is not allowed if the key is already in the pressed state, so both `#{1(exclam)}` and `#{exclam(1)}` are invalid
* the whole combo string …
> Rework handling of key combos

- .travis.yml
Building pyobjc-framework-Cocoa fails if Cython is installed, see: https://github.com/pypa/setuptools/issues/488
This is fixed by upgrading setuptools to >=19.6.
> travis: fix possible OSX build failure

- plover/log.py
- plover/main.py
Default levels:
- log and file handler: info
- print and gui handlers: warning
When the command line switch is used, it changes the global log level as well as the print/file handlers level.
This way the log file will by default contains a few useful traces.
> log: tweak levels

- plover/app.py
- plover/dictionary/loading_manager.py
- plover/gui/keyboard_config.py
- plover/machine/geminipr.py
- plover/machine/keyboard.py
- plover/machine/passport.py
- plover/machine/registry.py
- plover/machine/stentura.py
- plover/machine/treal.py
- plover/machine/txbolt.py
- test/test_passport.py
* change machine classes names to be more descriptive (instead of using `Stenotype` for all classes)
* add a few engine debug traces (output enabled/disabled, machine stopped/started)
* add a trace on dictionary load
> Small tweaks to improve debugging

- plover/machine/txbolt.py
- plover/main.py
- plover/oslayer/osxkeyboardcontrol.py
- setup.py
Fixes #189 #258 
App Nap slows down apps when they aren't in the foreground, which really messes up Plover's sleeps. With appnope, we tell the OS that we don't want to be slowed down, and in turn our sleeps no longer "get long" after not being the foreground application for a time.
The result is that the TX Bolt strokes are no longer "held back" and also the output code can use a regular sleep instead of the hacky busy loop.
> Disable App Nap on OSX

- plover/oslayer/osxkeyboardcontrol.py
Use `key_combo.KEYNAME_TO_CHAR`. This address the last point of #533.
Note: untested!
> Improve OSX `send_key_combination`

- plover/formatting.py
- test/test_blackbox.py
Fix #535.
Use case: when `{*($c)}` is used after stroking `1.2` (with 3 separate strokes), the formatter will try to undo 1 action only with `text` set to `2` and `word` set to `1.2`, with one action replacing `1.2` by `$1.20`. So we need to take `action.word` into account when rendering the initial (previous) text.
> formatting: check an action word too when handling replace

- plover/oslayer/osxkeyboardcontrol.py
Refactor the code to read a little simpler, putting the cleanup code after the loop stops instead of in the cancel method.
> Prevent crash on OSX caused by freeing up resources too quickly

- plover/gui/config.py
Changed the vertical alignment of the dictionary pathes in the "Dictionary" tab from top to center.
Looks nicer.
Debian (LMDE)
> Changed the vertical alignment of the dictionary pathes to center

- plover/oslayer/xkeyboardcontrol.py
This corrects the keycode for backspace on X server, previously it was set to left control's keycode.
> Fix x server backspace keycode.

- plover/oslayer/osxkeyboardlayout.py
@Achim63 noticed that keyboard watching wasn't working on his system. I believe the notification I was using was not fired in all cases, whereas the legacy Carbon API is always fired.
I also noticed that I forgot to set the visibility of some internal functions and that has been cleaned up.
> Improve macOS keyboard watching support

- plover/gui/dictionary_editor.py
It's too buggy:
- it does concurrent accesses to the GUI, a recipe for crashes on Linux with GTK
- it allows starting multiple concurrent filter threads
- just moving the mouse over the table will generate a bunch of calls to the dictionary store, so if you do that while the filter thread is doing it's thing, you get a bunch of errors
This should fix #540.
Tested on Arch Linux.
> gui/dictionary_editor: remove filter thread

- plover/machine/geminipr.py
Since the code is invalid, and would have raised an exception if executed, I think it's pretty safe to assume it's not useful...
> machine/geminipr: remove dead code

- plover/app.py
- test/test_engine.py
Make sure 'machine_class/machine_options/machine_mappings' members are only set if 'machine' is. 
Use case: both machine_class/machine_options are valid and the machine instance is correctly initialized, but setting the mappings fails.
> app: improve Engine.set_machine

- plover/config.py
- plover/gui/keyboard_config.py
- test/test_config.py
The keymap is a dictionary mapping action to keys. Previously, a string would be returned when the keymap is set in the configuration, but a dictionary would be returned when not present (default keymap). 
Also allow a list of pairs (action, keys) on set or in the config.
> config: improve system keymap handling 

- plover/formatting.py
- test/test_blackbox.py
Found that entries with \n \r \t were not doing anything while working on my machine, made a failing test and fixed it.
> formatting: handle escape characters when creating atoms

- plover/app.py
- plover/gui/lookup.py
- plover/gui/suggestions.py
- plover/suggestions.py
Fixes two pet peeves of mine: #527 lookup window tooks things too literally and made finding translations a chore.
Now the lookup and suggestions windows will find text like " Pre-" as "{pre-^}"
Lookup window also can horizontally scroll (needs to be tested for behavior on Linux)
> Use alternate suggestions in lookup window

- plover/oslayer/xkeyboardcontrol.py
- setup.py
Use XInput to capture keyboard events; this allow filtering-out the XTest keyboard, and only capture other keyboards when suppressing; which in turn will make it possible to use XTest for all simulated events (and not just for sending key combos).
This improve compatibility with with Qt5 applications (modifiers are now correctly handled), window managers (e.g. Awesome run prompt), Xterm (it's not necessary to use allowSendEvents anymore), ...
> Improve Linux keyboard support

- plover/app.py
- plover/dictionary/base.py
- plover/dictionary/loading_manager.py
- plover/key_combo.py
- plover/machine/geminipr.py
- plover/machine/keyboard.py
- plover/machine/keymap.py
- plover/machine/passport.py
- plover/machine/txbolt.py
- plover/misc.py
- plover/oslayer/winkeyboardcontrol.py
- setup.py
- test/test_engine.py
- test/test_json_dict.py
- test/test_steno_dictionary.py
* fix `setup.py` so the testsuite can be run
* most of the testsuite is passing with Python 3; remaining things that need to fixed:
* config
* dictionary formats (JSON is no problem, RTF/CRE is the most problematic)
* and the Stentura code: this one is a biggy...
> more preliminary "safe" changes for Python 3 support 

- application/Plover.desktop
Added Keywords to the FreeDesktop application file.
N/A
Patched as part of the Debian packaging effort, to close out lint warnings.
Not significant enough to go to release notes.
Tested with desktop-file-validate.
> Add Keywords to FreeDesktop application file

- plover/translation.py
- change output so it's unambiguous (None vs "None")
- escape \n, \r, and \t (prevent line breaks in strokes.log entries)
> translation: tweak Translation.str/repr format

- plover/assets/main.json
Fix for the following issue in #400 
Incorrect entry for the backslash.
Old entry (results in `{^`):
```
"SPWHRAERB": "{^}\\{^}",
```
New entry (resulting in `\`):
```
"SPWHRAERB": "{^\\^}",
```
> Dictionary update: Fixed the entry for the backslash (`\`) symbol.

- plover/oslayer/osxkeyboardlayout.py
Because I was using a dictionary to store sequences, valid sequences that use the same key code twice were failing to print.
```
Name:		udiaeresis
Character:	ü
Sequence:	‘u’
Base codes:	‘32’
```
```
Name:		udiaeresis
Character:	ü
Sequence:	‘⌥u’, ‘u’
Base codes:	‘32’, ‘32’
```
> osxkeyboardlayout: fix test print code from omitting duplicate keys

- plover/misc.py
Simplify `characters` when not running a narrow Unicode build.
Note: we do not yet run the tests under Python 3, but the Linux Python 2 interpreter of the Travis build is already a wide Unicode version.
> misc: improve Python 3 support

- .travis.yml
- linux/README.md
- osx/bootstrap.sh
- plover/config.py
- plover/dictionary/rtfcre_dict.py
- plover/machine/stentura.py
- plover/oslayer/osxkeyboardcontrol.py
- plover/oslayer/xkeyboardcontrol.py
- setup.py
- test/test_config.py
- test/test_rtfcre_dict.py
- test/test_stentura.py
- windows/README.md
- windows/helper.py
Note:
* configuration: the changes include making sure the configuration file is saved as UTF-8, and string options are returned as Unicode
* RTF/CRE dictionaries: for lack of better RTF file format support, assume the encoding of RTF/CRE dictionaries is cp1252
* Stentura: we can't just replace the use of `buffer` with `memoryview` in Python 3 because it does prevent us from resizing the original `bytearray` when needed
> Last of the changes needed for core Python 3 support

- plover/machine/txbolt.py
I was speaking with a stenograph dev and he said that our TX bolt timeout is excessive…
> I assume if we're running at 9600 baud and 10 bits/byte (one start, 8 data, one stop) that's just over 1ms/byte (960 bytes/second - 1.042 ms/byte) - so no need to wait more than 1 or 2 ms - not sure what is in the code at the moment 
His own code uses 15 milliseconds. I discovered that I can put my Infinity Ergonomic into TX bolt mode and so I switched the timeout to 15 milliseconds and ran it for a couple days. No stroke splitting issues and the output is noticeably snappier.
> Reduce timeout for TX Bolt protocol

- plover/assets/main.json
Just changing this entry:
"AOEFT": "East",
to:
"AOEFT": "east",
so that there is an entry for lowercase "east".
(Issue #400: Dictionary errors)
> Dictionary entry for lowercase "east"

- plover/gui/log.py
Example use case: dbus is available, but not the notifications service:
```
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```
> gui/log: handle exceptions during platform handler init

- plover/steno_dictionary.py
- test/test_steno_dictionary.py
Will be used by the new UI to allow selecting the target dictionary when using the "Add translation" dialog.
> steno_dictionary: add optional target dictionary to set

- plover/config.py
- plover/misc.py
- test/test_misc.py
* move from `config` to `misc` so they can be reused in the new UI to simplify the display of paths
* support `~/` for user home directory
* add tests
> rework expand/shorten path helpers

- plover/log.py
- test/test_log.py
Sort stroke keys in log file.
Fixes #187
Before
```
2016-09-08 16:05:53,350 Stroke(A- -T P-)
2016-09-08 16:05:53,351 Translation(('PAT',) : "pat")
```
After
```
2016-09-08 22:15:33,197 Stroke(TAP : ['T-', 'A-', '-P'])
2016-09-08 22:15:33,198 Translation(('TAP',) : "tap")
```
> Sort stroke keys when logging

- plover/__init__.py
- setup.py
Update the license to explicitly state GPLv2+, instead of only GPLv2. This is an attempt to resolve our license conflicts; some of our libraries are GPLv3. For this change, we've received permission from all copyright holders in issue #336 
The wording was grabbed from https://pypi.python.org/pypi?%3Aaction=list_classifiers
Closes #336
> Update license to GPLv2+

- plover/machine/geminipr.py
- plover/machine/procat.py
- plover/machine/registry.py
- plover/system/english_stenotype.py
Add the ProCAT machine, thanks to David Graper for sending a handy little diagram from his Blaze: [BlazeKeyouts.pdf](https://github.com/openstenoproject/plover/files/468399/BlazeKeyouts.pdf)
When contacting ProCAT, the representative told me that the Flash, Blaze, Stylus I & II, Impression, and Xpression all use the same protocol. Thankfully that should mean we get support for them all.
While some ProCAT writers could emulate TX Bolt, it wasn't true of all of them. I believe the Blaze was the last to emulate another protocol.
We should add ProCAT machines to the list of supported writers.
Glen and I tested on Windows, but I'll leave further testing for the weekly -- I imagine it will work since we're just using the serial base class.
> Add ProCAT machine

- .travis.yml
- appveyor.yml
- setup.py
- windows/helper.py
Note: I removed the wxPython requirements in `setup.py` since it's not possible to require it on Windows, and we need to install it manually anyway on all platforms (because it's not installable through pip).
> add Python 3 (tests only) builds to AppVeyor and Travis CI

- plover/machine/keymap.py
- plover/machine/procat.py
Don't send the empty key as a string to keymap.py from the ProCAT machine.
Hopefully fixes #601 
Not tested.
> machine/procat: don't send empty string as key

- plover/oslayer/xkeyboardcontrol.py
Previously, both KeyPress and KeyRelease were ignored if there were any modifiers. This runs into the issue of a key "sticking" in a perpetually pressed state if the key is pressed without modifiers but released with modifiers.
This wouldn't be an issue in steno, but it creates problems when switching in and out of steno with `{PLOVER:TOGGLE}` and typing rapidly with a conventional keyboard layout. (See the GitHub issue referenced for further details.)
Fixes #597.
> Ignore only KeyPress when a modifier is set

- plover/oslayer/winkeyboardcontrol.py
> oslayer/winkeyboardcontrol: don't ignore key release with modifiers

- .travis.yml
- setup.py
* travis: fix `pip list` call: make sure we use the right version.
* setup: use custom patched version for `pyobjc-framework-Cocoa`; needed so it builds on Yosemite. Also use tarballs instead of VCS links to speed up the builds a little.
> tweaks for OS X builds

- plover/oslayer/osxkeyboardcontrol.py
Fix #597 on Mac as well. See #598 and #609.
> oslayer/osxkeyboardcontrol: don't ignore key release with modifiers

- plover/gui/log.py
Warning in question:
```
2016-10-29 23:25:36,812 [MainThread] ERROR: could not initialize platform gui log
Traceback (most recent call last):
File "plover\gui\log.py", line 18, in <module>
NameError: name 'handler_class' is not defined
```
> gui: fix spurious warning at startup on Windows

- plover/config.py
- plover/dictionary/base.py
- plover/dictionary/json_dict.py
- plover/dictionary/rtfcre_dict.py
- plover/engine.py
- plover/gui_qt/dictionary_editor.py
- plover/misc.py
- plover/resource.py
- plover/steno_dictionary.py
- plover/system/__init__.py
- plover/system/english_stenotype.py
- test/test_config.py
- test/test_misc.py
Rework the handling of the dictionaries configuration, so the setting is handled per system, and each system can define a list of default dictionaries to use.
So the configuration now looks like this:
```
[System: English Stenotype]
dictionaries = ["main.json", "commands.json", "user.json"]
```
And the system additional constants are:
``` python
DICTIONARIES_ROOT = 'asset:plover:assets'
DEFAULT_DICTIONARIES = ('main.json', 'commands.json', 'user.json')
```
The `DICTIONARIES_ROOT/DEFAULT_DICTIONARIES` split is in prevision of orthographic systems using a Python dictionary, e.g. with:
``` python
DICTIONARIES_ROOT = 'asset:plover_template_system:dictionaries'
DEFAULT_DICTIONARIES = ('asset:plover_template_system:dictionaries/ortho.py', 'main.json', 'user.json')
```
only `main.json` and …
> Plugins support: improve systems

- plover/gui_qt/main_window.py
Rely on `config_changed` hook, so the system is correctly setup before trying to show the paper tape.
> gui_qt: fix handling of `show_stroke_display` option

- plover/gui_qt/add_translation.py
I sort of decided to do this on a whim; we've had similar requests before but there's always some complexity involved that I didn't want to deal with. Namely, the "number of previous strokes/words to look at" option. Instead of dealing with that, I decided to just optimistically try and grab the last word or stroke if there was one. It's dead simple and seems to get the job done, and it doesn't get in the way of the previous flow; if you have the translation window set to invisible, the pre-populated fields won't get in the way due to selection.
> gui_qt/add_translation: pre-populate with last word or stroke

- plover/engine.py
- plover/registry.py
Add support for custom commands to the plugin system. Note that those are only supported when output is enabled. See [here](https://github.com/benoit-pierre/plover/compare/plugins_support...benoit-pierre:priority_dict) for an example re-implementing #605.
> Plugins support: command

- plover/oslayer/xkeyboardcontrol.py
Look at Xinput pointer devices too, as some keyboards (like the VicTop mechanical gaming keyboard) register 2 devices, including a pointer device with a key class (to fully support NKRO).
Fix #644.
@GuiltyDolphin: can you make sure the (slightly refactored) code still work?
> oslayer/xkeyboardcontrol: fix support for some NKRO keyboards

- plover/gui_qt/suggestions_dialog.py
Fix empty text actions erasing entire suggestions word string when being removed. There's a similar check in the loop a few lines down, so this was probably just missed whenever that change was made.
Fixes #618
> Fix suggestions handling of empty text actions

- setup.py
Temporarily lock to 3.1.1 until 3.2.2 is released to fix builds.
> Lock down PyObjc

- bootstrap.sh
- osx/README.md
PyInstaller doesn't work with Python 3.6 yet, attempt to checkout Python 3.5's formula until https://github.com/pyinstaller/pyinstaller/issues/2331 is fixed.
> Freeze Homebrew for Python 3.5

- plover/formatting.py
- plover/translation.py
- test/test_blackbox.py
- test/test_formatting.py
- test/test_translation.py
Pass more state from the translator to the formatter so the output code can be simplified (by only taking into account an action text and replace fields). Supersede #666.
> Translation with more state

- plover/config.py
- plover/engine.py
- plover/gui_qt/config_window.py
- plover/registry.py
- test/test_config.py
- test/test_engine.py
Add support for extension plugins.
Minimal code for an extension:
```python
class Extension(object):
def __init__(self, engine):
pass
def start(self):
pass
def stop(self):
pass
```
An extension must be explicitly enabled by the user. It will be automatically initialized  and started/stopped when (re-)configuring the engine.
Use cases:
- monitoring external events (tracking application focus to automatically enable/disable Plover or maintain per application states)
- listening to a control socket for commands
- creating more complex plugins that are not state less (an extension could dynamically register other plugins)...
> add extension support to the registry

- plover/registry.py
- to allow for cleaner plugins code when implementations differ for each platform
- so a plugin can declare entrypoints for only supported platforms
Example: `plover.linux.command` instead of `plover.command` for declaring a Linux only command.
> registry: add platform specific entrypoints

- plover/resource.py
Don't use `unicode`, as it only works with Python 2.
> resource: fix resource_string

- plover/gui_qt/main_window.py
Otherwise the combo box will be display the first item (`Gemini PR`) until dictionaries are loaded and the machine is setup.
> gui_qt: fix initial machine type display

- plover/gui_qt/main_window.py
Just destroying the dialog is not enough: signals are not automatically disconnected, so for example the paper tape will keep on being notified about strokes.
> gui_qt: make sure signals are not delivered to closed tools

- plover/oslayer/processlock.py
- plover/oslayer/winkeyboardcontrol.py
- plover/oslayer/winkeyboardlayout.py
- plover/oslayer/wmctrl.py
- setup.py
- windows/README.md
- windows/helper.py
- it's a pain to install (you can't use pip) and the installation is not contained to Python site-packages (DLLs in one of Windows system folders)
- we can easily change code that uses it to ctypes
Tested with a Windows 10 VM.
> get rid of the dependency on pywin32

- plover/config.py
- plover/dictionary/base.py
- plover/engine.py
- plover/gui_qt/add_translation.py
- plover/gui_qt/config_window.py
- plover/gui_qt/dictionaries_widget.py
- plover/gui_qt/i18n.py
- plover/gui_qt/lookup_dialog.py
- plover/gui_qt/main_window.py
- plover/gui_qt/paper_tape.py
- plover/gui_qt/suggestions_dialog.py
- plover/main.py
- plover/registry.py
- plover/system/__init__.py
- setup.py
- test/test_config.py
- test/test_engine.py
Load all plugins at startup, instead of dynamically as needed:
- I think it's safe to assume that if a plugin is installed, it means the user is going to want to use it, so it's better to fail early if there's a missing dependency rather than suddenly, e.g. when the user tries to use a command
- this make it possible to export metadata for each plugin (help/doc) to provide a more user-friendly UI
> rework plugins handling

- .travis.yml
- appveyor.yml
- bootstrap.sh
- osx/README.md
- plover/gui_qt/i18n.py
- setup.py
- windows/README.md
- windows/helper.py
- windows/hook-plover.py
Rational:
- Python 2 builds on those platform are narrow Unicode builds
- PyQt5 wheels are only available for Python 3
- those Python 2 builds are not really useful from a test standpoint, since the testsuite does not really test our platform specific code
> drop Python 2 support on Windows / OS X

- osx/README.md
Found out we didn't need sudo to run with the keyboard machine in development, got carried away with rewording and organizing the content.
> Remove sudo and reword Mac README

- plover/oslayer/osxkeyboardcontrol.py
For some reason, after upgrading to Sierra, the control key doesn't act globally unless accompanied by flags that are present when pressing the physical control key.
Note: it does work locally (the current window catches events), but to use globals like Mission Control and Spectacle it needs this extra flag.
Also, as of Sierra having an output source seems to break control in globals too.
Not going to lie, it feels like magic.
TODO: try this on an older OS to make sure I didn't break anything.
> osxkeyboardcontrol: fix control key on macOS Sierra

- plover/gui/util.py
- plover/oslayer/osxkeyboardcontrol.py
- plover/oslayer/processlock.py
- plover/oslayer/winkeyboardcontrol.py
- plover/oslayer/winkeyboardlayout.py
- plover/oslayer/xkeyboardcontrol.py
- setup.py
- windows/README.md
- windows/helper.py
* lock down PyObjc version
* NKRO fix for Linux
* control key fix for macOS Sierra
* fix for missing modifiers in combos on macOS
Note: for some reason the Python 3 build on AppVeyor fails because of a permission error when installing pywin32... ¯\\_(ツ)_/¯
> Cherry picks for 3.1.1

- archlinux/PKGBUILD
- bootstrap.sh
- setup.py
Now that `hidapi` is available for Python 3 too, there's no reason to stick to Python 2 anymore.
Note: I also fixed the fact that `gui_none` was missing in setup's list of packages.
> update Arch Linux support

- plover/machine/txbolt.py
> machine/txbolt: ignore sixth bit in #ZDST stroke packet

- plover/oslayer/osxkeyboardlayout.py
As usual, venturing into this file with a fresh mind allowed for some fixes.
- If a layout's Unicode mapping is None, like with Japanese, then get its ASCII representation. Fixes a crash.
- Keys with unknown deadkey states are ignored, allowing Hindi and sammy-nes to not crash...but the behavior may be undefined.
- Rework the favored key sequence logic to prefer longer sequences **if** the shorter sequence has a bad modifier compared to both of the other one.
- Fill in a missing piece of the layout reading that skipped some letters where the deadkey is explicitly set to nothing (odd but true?!).
Fixes #720, #627 -- need to get confirmation from both authors.
> osxkeyboardlayout: various fixes

- plover/config.py
- plover/gui_qt/paper_tape.py
- plover/gui_qt/suggestions_dialog.py
- test/test_config.py
Add saving and restoring of ontop setting to suggestions dialog and paper tape using QSettings.
Fix restoring of paper tape style setting (was only restoring the text label).
Remove the config options for ontop and paper tape style from the main config.
This restores behaviour lost when changing from wxWidgets to Qt.
Linux Mint 17
> Fix GUI tools' settings' persistence

- plover/dictionary/base.py
- plover/gui_qt/main_window.py
- plover/registry.py
So there's no need to do it everywhere `registry.list_plugins` is used. This fixes the display order of machines in the UI.
> registry: sort `list_plugins` result

- plover/gui_none/main.py
- plover/gui_qt/main.py
- plover/log.py
- plover/main.py
- plover/oslayer/log_dbus.py
- plover/oslayer/log_plyer.py
- setup.py
Do it before loading plugins, so the user get some feedback on errors.
Note: this still leave Windows users without feedback if an error occurs during the initialization (no platform specific log handler).
> log: initialize platform handler earlier

- setup.py
Plyer 1.3.0 broke notifications on Windows... See https://github.com/kivy/plyer/issues/318.
> setup: pin Plyer's version

- plover/oslayer/osxkeyboardcontrol.py
Fix #732 
- Go back to using our old output source as the NULL one causes #732
- Through experimentation, I think that Sierra requires secondary Fn mask for certain keys. This includes escape, the F-row, and the extended keys (number pad, home, end, arrows, etc.)
I'm still soaking this to see if there are any quirks.
> Mac keyboard control fixes for Sierra, again

- .travis.yml
- archlinux/PKGBUILD
- bootstrap.sh
- debian/changelog
- debian/control
- linux/appimage.sh
- linux/appimage_blacklist.txt
- linux/debuild.sh
- linux/makepkg.sh
- linux/packpack.mk
- linux/packpack.sh
- rpm/package.spec
- setup.py
- utils/download.py
- utils/functions.sh
- utils/install_wheels.py
- utils/trim.py
- windows/dist_blacklist.txt
- no more brew on macOS: the official Python installer for 3.5 is used instead
- drop eggs and deb on Linux: instead generate an [AppImage](http://appimage.org/)
- add [packpack](https://github.com/packpack/packpack) support: this can be used to generate the AppImage, a deb for Ubuntu Trusty/Xenial, an Arch Linux package, or a RPM for Fedora Rawhide
> switch to official Python installer on macOS + rework artifacts on Linux

- test/test_misc.py
MiscTestCase.test_dictionary_path() passes conf.CONFIG_DIR through os.path.realpath() before using it, since the functions it's testing do the same. This fixes #661.
The tests pass with this patch, but fail without it, both on upstream master and on the branch in #738.
This pull request replaces #671, which was closed because I accidentally deleted my copy of the branch.
> Test for config directory expands symlinks

- plover/system/__init__.py
- plover/system/english_stenotype.py
- test/test_blackbox.py
Fix system SUFFIX_KEYS getting put into a set, which loses all reliable ordering.
Order english stenotype SUFFIX_KEYS into reverse steno order (automatic suffixes which don't break steno order should be picked before those that do).
> Fix inconsistent ordering of automatic suffix keys

- plover/suggestions.py
The returned value is now a list, not a set.
> suggestions: fix use of casereverse_lookup

- plover/dictionary/loading_manager.py
- plover/engine.py
- plover/gui_qt/add_translation.py
- plover/gui_qt/dictionaries_widget.py
- plover/oslayer/xkeyboardcontrol.py
Some minor Python tidies:
* Remove unused imports and an unused variable
* Fix two places where `log` was being with `%`-formatting instead of comma-formatting.
* Fix a typo in a variable name.
It doesn’t fix an issue, this is just general code hygiene.
Just running a Python linter on OS X.
> A few Python tidies

- plover/gui_qt/dictionaries_widget.ui
On Ubuntu Trusty, with PyQt5 version 5.2.1, connecting the signal for `on_dictionary_changed` fails:
```python
Unexpected error: Traceback (most recent call last):
File "/home/bpierre/progs/src/plover/plover/main.py", line 73, in main
code = gui.main(config)
File "/home/bpierre/progs/src/plover/plover/gui_qt/main.py", line 93, in main
app = Application(config, use_qt_notifications)
File "/home/bpierre/progs/src/plover/plover/gui_qt/main.py", line 64, in __init__
self._win = MainWindow(self._engine, use_qt_notifications)
File "/home/bpierre/progs/src/plover/plover/gui_qt/main_window.py", line 44, in __init__
self.dictionaries = DictionariesWidget(engine)
File "/home/bpierre/progs/src/plover/plover/gui_qt/dictionaries_widget.py", line 38, in __init__
self.setupUi(self)
File …
```
> gui_qt/dictionaries_widget: workaround PyQt5 5.2.1 bug

- plover/steno_dictionary.py
- test/test_steno_dictionary.py
Mark a dictionary as read-only if its file is read-only.
> steno_dictionary: mark readonly if file is

- plover/dictionary/loading_manager.py
- plover/engine.py
- plover/steno_dictionary.py
- test/test_engine.py
- test/test_loading_manager.py
- test/test_steno_dictionary.py
- test/test_translation.py
- test/utils.py
The `dictionaries_loaded` hook will be now potentially triggered 2 times during an update:
- after unloading outdated dictionaries
- after (re)loading new/updated dictionaries
This way the GUI can show a `reloading` icon for dictionaries being reloaded because they were externally modified.
> show reload icon for outdated dictionaries

- debian/control
- linux/README.md
- linux/packpack.sh
The version of PyQt5 available on Ubuntu Trusty is too old.
> Drop native support for Ubuntu Trusty

- plover/machine/keyboard.py
- setup.py
- test/test_keyboard.py
Instead of tracking which steno keys have been pressed/released, track the raw keys. This fix those edge cases (with + and - for press and release respectively):
- `+a +q -a` result in `S-` but a key is still held down
- `+a +r -a +a -r` result in `K-` but a key is still held down
- with arpeggiate mode enabled, `+a +space -space -a` does not work
> machine/keyboard: fix a number of edge cases

- plover/main.py
- plover/oslayer/config.py
- plover/registry.py
- setup.py
Stop using pkg_resources' find_plugins, and switch to simply prepending a new entry to the Python path, as it will make managing plugins easier:
- now that plugins' entrypoints are resolved on startup, we don't need `find_plugins` to detect broken (due to missing dependencies) plugins
- broken plugins sill need their distributions to be added to the path; so they are visible by pip and can be uninstalled/updated
> Rework plugins

- plover/oslayer/osxkeyboardcontrol.py
Seems at some point I accidentally suppressed key up events generated by Plover causing them never to be released.
Fixes #779
> osxkeyboardcontrol: don't suppress keyup events created by Plover

- plover/oslayer/config.py
Needed by the plugins manager to correctly support source installs.
> oslayer/config: add PLUGINS_BASE

- linux/appimage/build.sh
There's one report of issues on Debian when it is enabled. Since it's always possible to explicitly add it to the Python path, it's better to disable it by default.
> linux/appimage: disable user site-packages

- plover_build_utils/install_wheels.py
The option must be passed to `pip wheel` too, otherwise some unnecessary packages may be cached (e.g. when creating the distribution: PyQt5 5.9, even though 5.8.2 is actually used).
> utils/install_wheels: fix handling of `--no-deps`

- osx/dmg_resources/settings.py
- plover_build_utils/dmgbuild.sh
- plover_build_utils/download.py
- plover_build_utils/functions.sh
- plover_build_utils/get_pip.py
- setup.py
The new version supports automatically sizing the final image, which will make things easier when bundling the plugin manager and the additional required PyQt modules (like the web engine).
> osx: update dmgbuild

- plover_build_utils/functions.sh
Use one install command for Plover, its dependencies, and the standard plugins, so we don't end up caching some unnecessary wheels. (#800 only moved the problem from the command for installing Plover's wheel to the next command for installing standard plugins).
> utils/functions: improve distribution bootstrapping

- ci/circle.sh
- ci/travis.sh
- linux/appimage/blacklist.txt
- linux/appimage/build.sh
- osx/app_resources/dist_blacklist.txt
- osx/make_app.sh
- plover_build_utils/functions.sh
- requirements_distribution.txt
- requirements_plugins.txt
- setup.py
- windows/dist_blacklist.txt
* update PyQt5 to latest LTS version (5.9)
* add `plover-plugins-manager` to standard plugins: this means bundling-in the Qt web engine
* updated distributions Python version to 3.5.4
* PyQt5 system dependencies are no longer bundled, as this can cause issues on a number of distributions
Tested:
* AppImage on Arch Linux, Ubuntu Trusty/Xenial, and Fedora 22/25/Rawhide: starting the plugins manager on Fedora 25/Rawhide crash (SSL error, the distribution's pip does not work either...)
* Windows setup on Windows 10
> add plugins manager to the standard plugins

- plover/formatting.py
- test/test_blackbox.py
- test/test_formatting.py
Blackbox tests:
- make each test simpler
- improve error reporting
- shorten output size for failed tests
- support incremental checking of the output
Formatting tests: use pytest with parametrization so it's easier to select tests.
> Rework blackbox/formatting tests

- plover/gui_qt/add_translation_dialog.py
- plover/gui_qt/add_translation_dialog.ui
- plover/gui_qt/add_translation_widget.py
- plover/gui_qt/dictionaries_widget.py
- plover/gui_qt/lookup_dialog.py
- plover/gui_qt/lookup_dialog.ui
- plover/gui_qt/main.py
- plover/gui_qt/main_window.py
- plover/gui_qt/main_window.ui
- plover/gui_qt/suggestions_dialog.py
- plover/gui_qt/suggestions_dialog.ui
- plover/gui_qt/suggestions_widget.py
Use Qt designer builtin support (to [promote widgets](http://doc.qt.io/qt-5/designer-using-custom-widgets.html) to a custom class), instead of manually replacing the widget at initialization time.
Note: also set the engine at the QApplication level, so custom widget that needs it can access it through `QApplication.instance().engine`.
@morinted: you'll have to update your dictionary builder plugin.
> gui_qt: rework handling of custom widgets

- plover/gui_qt/add_translation_widget.py
- plover/steno.py
- plover/suggestions.py
- escape translations/strokes to prevent interpretation (see: https://github.com/openstenoproject/plover/issues/773#issuecomment-306220676)
- style translations/strokes to make the whole text easier to read
Example:
> gui_qt/add_translation: fix widget translation label

- plover/gui_qt/config_window.py
- plover/machine/base.py
- plover/machine/keymap.py
- test/test_passport.py
Make configuration easier: instead of mapping actions to keys (making it impossible to know what keys are valid and easy to screw up by using the wrong format), bind keys to actions (with a combo for easy selection of all valid actions).
Before:
After:
> rework keymap configuration widget

- archlinux/PKGBUILD
- plover/registry.py
- setup.cfg
- test/test_blackbox.py
We don't need to use six anymore or directly require it.
> drop Python 2 leftovers

- test/test_formatting.py
Although not documented, it's possible to easily mark a parametrized test input as failing by wrapping it with `pytest.mark.xfail()`.
> test: minor simplification of formatting tests

- plover/formatting.py
- plover/gui_qt/add_translation_widget.py
- plover/gui_qt/suggestions_dialog.py
- plover/system/__init__.py
- plover/translation.py
- test/test_blackbox.py
- test/test_formatting.py
Greatly factorize the code, by changing the way spaces are handled: stitch actions at the output stage, so there's no need for 2 different code paths (space after and spaces before) when converting atoms to actions.
Also rework last word handling:
- for suffixes: store the raw un-cased word (sans prefix, as before)
- for other use-cases (retrospective commands): rely on an helper to generate the last n words from previous translations.
Fix #554 and #741.
> rework formatting code

- plover/gui_qt/dictionaries_widget.py
> gui_qt/dictionaries: fix buttons state after deletion

- test/test_blackbox.py
#287 and #470 have been fixed, add corresponding blackbox tests to prevent regressions.
> Add blackbox tests for #287 and #470

- setup.py
Otherwise an error will occur when launching the plugin manager if vcruntime140.dll is not already available system wide.
> windows: fix missing Visual C++ Redistributable DLL error

- plover/engine.py
This will prevent them from being selectable when adding a translation. Fix #840.
> engine: mark errorred dictionaries as readonly

- plover/gui_qt/main.py
Fixes #839 
```python
```
Tested:
- Dock quit
- Menu bar quit
- Plover quit
- Terminal process quit
- Activity Monitor Quit
- Quitting a .app the same ways
> Quit engine when quitting QCoreApplication to prevent Mac freeze

- plover/gui_qt/add_translation_widget.py
> gui_qt/add_translation: fix escaping of \n and \t

- plover/machine/base.py
- plover/machine/geminipr.py
- plover/machine/passport.py
- plover/machine/procat.py
Add an `_iter_packets(packets_size)` helper to `SerialStenotypeBase`: yield packets of `packets_size` bytes until the machine is stopped. To workaround the fact that the Toshiba Bluetooth stack on Windows does not correctly handle the read timeout setting (returning immediately if some data is already available):
- the effective timeout is re-configured to `timeout/packet_size`
- multiple reads are done (until a packet is complete)
- an incomplete packet will only be discarded if one of those reads return no data (but not on short read)
Update the Gemini PR code to use this new method and reject invalid packets. Fix #846.
Note: the Procat code should probably be updated to do the same.
> Improve Gemini PR, Passport, and Procat support

- plover/gui_qt/add_translation_widget.py
- plover/macro/repeat.py
- plover/macro/retrospective.py
- plover/macro/undo.py
- plover/registry.py
- plover/translation.py
- setup.cfg
- test/test_blackbox.py
- test/test_translation.py
* factorize the translator's code
* improve retrospective asterisk toggle
* add support for macros
* allow mapping the system's undo stroke to a standard translation and mapping undo to different strokes (using the new `:undo` syntax for macros)
Fix #849.
> Translator rework

- plover/formatting.py
- plover/registry.py
Example use case: [timestamp support](https://github.com/benoit-pierre/plover_vlc_commands/blob/2409e978ededdaf628dbd3bd972a356d9873e7a9/plover_vlc_commands.py#L60) for the plover_vlc_commands plugin.
> add support for meta plugins

- plover/formatting.py
- test/test_blackbox.py
- test/test_formatting.py
Alternative too #860.
* don't carry on retro upper
* more consistent handling of words: use the same word definition for `_rightmost_word`
* better detection of word boundaries: extend check to all whitespace characters, not just space
Fix #836 and #837, but **not** #838 (with this implementation the behavior is expected).
> formatting: change word handling, take 2

- plover_build_utils/testing.py
I noticed that after exporting support for blackbox tests the assertion message on failure changed from:
```
_____________________________ TestBlackboxReplays.test_carry_upper_spacing6 ______________________________
bb = <test.test_blackbox.TestBlackboxReplays object at 0x14cb56555f98>
>   new_f = lambda bb: (f(bb), replay(bb, name, test))
E   AssertionError: test_carry_upper_spacing6
E
E       "TEFT": "{<}test",
E       "W-G": "{^ing\nwith}",
E
E     > TEFT/W-G  ' TESTING\nWITH'
E       W-G       ' TESTING\nwithing\nwith'
E
E   assert ' TESTING\nwith' == ' TESTING\nWITH'
E        TESTING
E     - with
E     + WITH
test/test_blackbox.py:117: AssertionError
================================== 1 failed, 132 passed in 0.91 seconds ==================================
```
to:
``` …
```
> utils: tweak blackbox test assertion message

- plover/gui_qt/paper_tape.py
- requirements_distribution.txt
- setup.cfg
Use the wcwidth package to calculate each character's width.
> gui_qt/paper_tape: improve handling of non-Latin keys

- plover/log.py
If a system contains unicode keys in strokes or outputs unicode via a dictionary then a UnicodeEncodeError is thrown due to character map encoding issues and that entry is not logged properly (provided stroke / translation logging is enabled).
I set the file handler for logging to always open as utf-8 rather than no encoding so that it does not run into the issue.
I have tested on Windows 10 and unicode characters show up in the log as expected now with no errors thrown.
> log: open log file as utf-8 to handle unicode strokes and output.

- archlinux/PKGBUILD
- plover/main.py
- plover/oslayer/config.py
- plover/registry.py
- plover_build_utils/setup.py
- requirements_distribution.txt
- rpm/package.spec
- setup.cfg
- setup.py
Trying to ensure that `setup.py` is called with the right version of setuptools is not possible in all cases when using `__requires__`: if the version wanted is installed but not the activated version (e.g. because an older version from the user site-packages takes precedence), then it will be activated too late (`pkg_resources` has already been loaded, and potentially `setuptools` too).
Additionally, setuptools now supports installing from wheel, so rework how `setup_requires` are handled; implementing `plover_build_utils.setup.ensure_setup_requires`. To be used at the beginning of `setup.py`, it will ensure:
- the correct version of setuptools is active
- the setup requirements are installed and can be imported
This make installation from source using pip possible even if the …
> rework `setup_requires` handling (again) and make QT GUI optional

- plover/config.py
- plover/engine.py
- plover/gui_qt/config_window.py
- plover/gui_qt/machine_options.py
- plover/machine/base.py
- plover/machine/keyboard.py
- plover/misc.py
- test/test_config.py
- test/test_engine.py
- test/test_misc.py
Right now, configuration settings are only validated for correctness when loading from the configuration file. While this is not really an issue when those are changed through our GUI, plugins can now update the configuration (e.g. the `plover_dict_commands` plugin).
This PR overhaul the way the configuration is handled so:
- all custom set/get accessors are removed in favor of a standard mapping API:
```
config.set_machine_type("Keyboard") -> config["machine_type"] = "Keyboard"
```
- all options are validated on set/update too
- updates are all or nothing: nothing is updated if one of the options is invalid
> Config rework

- linux/appimage/apprun.sh
- linux/appimage/build.sh
- remove the need for ccache being installed
- fix possible linking errors
> linux/appimage: improve support for package installs from source

- linux/appimage/apprun.sh
- linux/appimage/build.sh
- osx/app_resources/plover_launcher.sh
- osx/make_app.sh
- plover/dist_main.py
- plover/main.py
- plover/oslayer/config.py
- setup.py
In order to support #907 and fix https://github.com/benoit-pierre/plover_plugins_manager/issues/4, this PR drop the custom plugins directory handling in favor of a dedicated launcher for distributions:
* when Plover is installed with pip or a distribution package manager, then user plugins are assumed to be installed in the standard user site (and can be installed/updated/removed from there with the plugins manager)
* when Plover is run through a distribution, then we want to be isolated from an existing Python installation: `PYTHONUSERBASE` is set according to Plover's configuration directory (so portable mode is respected). In this mode, user plugins can be disabled by launching with `--no-user-plugins` (the embedded distribution plugins will still be loaded).
This will require a new …
> Rework plugins directory handling

- plover/gui_qt/main_window.py
If `_NET_ACTIVE_WINDOW` is not supported by the current window manager, then we can't track the currently focused window and should therefore not try to restore focus to it.
Fix #926.
> gui_qt: fix possible crash on Linux

- plover/misc.py
- plover/oslayer/winkeyboardcontrol.py
- test/test_misc.py
1. Windows requires that you split Unicode characters into surrogate pairs before submission to SendInput, if they are outside the BMP as the maximum size of the character point in SendInput is 16bits.
2. Split incoming Unicode characters into surrogate pairs if they are outside the BMP. This was done by hand based on the Unicode specification because Python appears to offer no means of splitting a surrogate pair without encoding to UTF-16, removing the BOM, and then manually cutting the bytes out and putting them back together.
> Fix Unicode characters outside of BMP on Windows.

- plover/gui_qt/dictionaries_widget.py
Fixes #896.
Added tooltips for the cases of
- loading
- favorite
- readonly
I left the error case as-is as it was showing a tooltip with the exception already. I wasn't sure on the exact messages to include in the tooltips, so I just took a shot at a short description of each state.
I ran `python setup.py extract_messages` to update the plover.pot file to include these new strings as well. It made some other changes outside of just line numbers for strings that have been added or no longer appear anywhere else; these appear fine at first glance to me.
> gui_qt: Add tooltips to dictionary icons

- plover/formatting.py
- test/test_blackbox.py
Account for the fact that casing may have changed. Fix #966.
> formatting: fix orthographic replacements

- MANIFEST.in
- plover_build_utils/setup.py
- pyproject.toml
- setup.py
Now that [PEP 518](https://www.python.org/dev/peps/pep-0518/) is supported by pip (`>=18.0`), we can use it for declaring build dependencies.
> setup: use PEP 518 support for build dependencies

- requirements.txt
- setup.cfg
Rational: Arch Linux just switched to Python 3.7.
> Fix Python 3.7 support

- plover/macro/retrospective.py
- test/test_blackbox.py
> macro: fix retrospective insert space with suffix keys

- plover/dictionary/json_dict.py
- test/test_json_dict.py
The POSIX definition of a text file requires that it end with a newline
character.  The JSON files created through e.g. the ADD_TRANSLATION
command do not conform to this definition; this commit fixes that.
> Add trailing newline when writing JSON dictionary

- plover/oslayer/winkeyboardcontrol.py
- plover_build_utils/get_pip.py
Fix #991 and possibly others relating to Unicode.
I finally tracked down the main issue with Unicode output being corrupted in certain Windows GUIs (including Plover's). When sending Windows messages for keyboard input, the code branches based on whether the character has a standard keycode or needs the special Unicode flag. For standard keycodes, it makes sure to send messages for each key without the KEYUP flag, then send each one with it to release them. For Unicode, however, it only sent the keydown messages.
This one was hard to track down because it only affected certain windows. Depending how the receiving framework handled the messages, it might either work fine, or it might cause the first Unicode character to get "stuck" down. Since the "normal" keycode sent with Unicode …
> Fix #991: add keyup events for Unicode characters on Windows

- plover/gui_qt/lookup_dialog.py
Automatically focus the input field and pre-select the previous input when the lookup window is activated.
Fixes #976
> focus the input field when the lookup window is activated

- plover/steno_dictionary.py
- test/test_steno_dictionary.py
Make sure an existing previous mapping is removed before updating it (so `reverse_lookup`/`casereverse_lookup` results are not erroneous).
Also slightly speedup `StenoDictionary.update` in the common case (when the dictionary being updated being updated is empty, e.g. when loading), to avoid the slowdown brought by the fix.
> steno_dictionary: fix `StenoDictionary.__setitem` implementation

- archlinux/PKGBUILD
No need to patch out the PyQt5 dependency anymore: the latest python-pyqt5 package now has the proper Python distribution metadata.
> Update Arch Linux PKGBUILD

- appveyor.yml
- ci/circle.sh
- ci/travis.sh
- linux/appimage/build.sh
- osx/app_resources/dist_blacklist.txt
- osx/make_app.sh
- requirements.txt
- requirements_distribution.txt
- requirements_plugins.txt
- setup.cfg
- setup.py
- test/test_rtfcre_dict.py
- windows/helper.py
Initially, the idea was to stay on PyQt5 5.9.x (since Qt 5.9 is supposed to be a LTS version), and only update to new point releases, but PyQt5 does not follow that, so we might as well update to the latest version.
Note: there's no QtWebEngine support with recent win32 builds of PyQt5, hence the switch to generating a 64bits distribution.
I've tested locally the new AppImage on Arch Linux and Ubuntu Trusty, and the new Windows installer/distribution on a Windows 10 VM, someone need to test the macOS image.
> Update plugins, development and distributions requirements, and the distributions' Python version

- plover/gui_qt/main_window.py
- plover/gui_qt/main_window.ui
- plover/gui_qt/resources/folder.svg
- plover/gui_qt/resources/resources.qrc
Fixes #697.
I added an entry for "Open config folder" to the File menu that opens up the configuration folder.
The icon used is from [Icons8 Flat Color Icons](https://github.com/icons8/flat-color-icons).
Perhaps the oddest part here is the use of webbrowser.open to open the folder. os.startfile is Windows exclusive, so I searched around for cross platform ways to open folders and files and ended up on that standard library function accomplishing the desired behavior despite the name. Alternatively something like this could be implemented, but I figured if webbrowser.open works it's simpler to rely on it:
```python
import subprocess, os
if sys.platform.startswith('darwin'):
subprocess.call(('open', filepath))
elif os.name == 'nt':
os.startfile(filepath)
elif os.name == 'posix': …
```
> gui_qt: Add open config folder action

- plover/steno_dictionary.py
Fix #897.
I came across this method during my search code revisions and my IDE always marked it with warnings. Now that I see there's an issue with the program attempting to save dictionaries marked as read-only, it's a simple fix.
> Fix read-only dict saving (#897)

- setup.py
Ensure `plover`/`plover_build_utils` can be imported even when`pip>=19.0` PEP 517/518 build isolation is used.
> setup: fix support for pip>=19.0

- plover/gui_qt/config_window.py
- plover/gui_qt/machine_options.py
Fix #739
1. Always scan serial ports when rendering machine serial options
2. If the current value is None, set the first scanned port. That port was previously getting displayed but not saved because the "on_port_changed" method was being called before the config_window was connected. A singleShot is used to scan the ports again which will set the first port in settings.
> Save default machine config options, including serial ports

- plover/gui_qt/config_window.py
Make sure unsaved configuration data is discarded.
Steps to reproduce:
- select a serial machine
- change a setting, but don't apply/save the change
- switch to the keyboard machine -> crash
> gui_qt/config: fix a possible crash

- archlinux/PKGBUILD
> archlinux: add missing `qt5-svg` dependency

- plover/gui_qt/main_window.py
Only register a shortcut for the main (menu) action, and not for the other (toolbar related) actions to avoid duplicate shortcuts.
Supersede #1010 and #1048.
> Fix tools main shortcuts

- plover/gui_qt/dictionary_editor.py
Fixes #1040.
It appears that `QTableView` has problem when the model is modified while it's in edit state.
> Exit edit mode before modifying the model

- plover_build_utils/testing.py
- test/test_blackbox.py
Starting with 4.2.0, the support for xunit-style setup functions has changed; more precisely the order in which they are called.
For some reason, this can break blackbox tests:
* patch one of the blackbox test to fail:
```diff
diff --git a/test/test_blackbox.py b/test/test_blackbox.py
@@ -985,7 +985,7 @@ def test_upper6(self):
'P-': '{foo^}',
'-S': '{^bar}',
-        TP*U/P-/-S  " FOOBAR"
+        TP*U/P-/-S  " FooBaR"
'''
def test_upper7(self):
```
* run all the blackbox tests (`./test.sh test/test_blackbox.py`): `test_upper6' fails has expected
* run only `test_upper6` (`./test.sh test/test_blackbox.py test_upper6`): the test now passes!
So change the implementation to use a decorator, which is both compatible with pytest>=4.2.0 and more pythonic.
> utils: fix blackbox tests framework to work with pytest>=4.2.0

- plover/config.py
- test/test_config.py
The call to get the default value was using the wrong parameters + handle the case where the wrong type is used.
> config: fix keymap validation

- plover/steno_dictionary.py
- test/test_steno_dictionary.py
Don't stop at the first result, potentially ignoring lower priority dictionaries. This also tweak the `StenoDictionary` code to be slightly faster on load.
Timings:
* `main.json` (4.02 MiB, 147424 entries): `0.781s` -> `0.625s`
* `german_palantype.json` (58.29 MiB, 1466824 entries): `13.492s` -> `10.511s`
* magnum.json (18.81 MiB, 616946 entries): `5.053s` -> `4.177s`
* `magnum.rtf` (45.8 MiB, 616946 entries): `22.953s` -> `22.731s` (yes RTF is still slow as hell, much better with the new parser: `14.338s`)
> steno_dictionary: fix `StenoDictionaryCollection.casereverse_lookup`

- ci/circle.sh
- ci/travis.sh
- linux/appimage/apprun.sh
- linux/appimage/blacklist.txt
- linux/appimage/build.sh
- linux/appimage/pyinfo.py
- linux/packpack.mk
- linux/packpack.sh
- plover_build_utils/setup.py
- setup.py
- windows/helper.py
This include the following change to the AppImage creation: Python is no longer built, instead the available version of `python3` is used. This way the compilation can be moved to the Docker image creation, for both faster AppImage build times and a faster interpreter (built with optimizations).
This rely on https://github.com/openstenoproject/plover-docker-images/pull/2 being merged.
AppImage timings: `16.586s` -> `14.826s` when loading `german_palantype.json` (58.29 MiB, 1466824 entries).
> Update distributions to Python 3.6.8

- plover/oslayer/xkeyboardcontrol.py
Enables the usage of ISO level 3 shift and thus makes possible to use the AltGr-modifier key found, for example on the Finnish keyboard. The usage is {#ISO_Level3_Shift(...)}.
> Load non-us keyboard related keysyms from xkb

- plover/system/english_stenotype.py
Stroking `RUS/-BLT` will result in "reducibility" instead of "reducability".
I know it's possible to get that word with `RUS/IBLT`, but this is for consistency with `"able": "ible"`.
> Add missing orthography rule alias

- .github/PULL_REQUEST_TEMPLATE.md
- MANIFEST.in
- NEWS.rst
- doc/developer_guide.rst
- doc/releases.rst
- news.d/api/1066.break.rst
- news.d/bugfix/1022.core.rst
- news.d/bugfix/1027.windows.rst
- news.d/bugfix/1038.dict.rst
- news.d/bugfix/1041.ui.rst
- news.d/bugfix/1061.ui.rst
- news.d/bugfix/1062.ui.rst
- news.d/bugfix/1065.core.rst
- news.d/bugfix/1066.core.rst
- news.d/bugfix/1096.dict.rst
- news.d/bugfix/897.ui.rst
- news.d/bugfix/991.windows.rst
- news.d/bugfix/995.core.rst
- news.d/feature/1009.ui.rst
- news.d/feature/1022.core.rst
- news.d/feature/1023.windows.rst
- news.d/feature/1025.core.rst
- news.d/feature/1036.ui.rst
- news.d/feature/1068.linux.rst
- news.d/feature/1082.linux.rst
- news.d/feature/981.ui.rst
- news.d/template.rst
- pyproject.toml
Add [towncrier](https://pypi.org/project/towncrier/) support: avoid the need to go spelunking through the log to create release notes. See the newly added documentation for usage.
I also added some news fragments for existing changes since the latest weekly, here is how those would be rendered (`towncrier --draft`):
```rst
v4.0.0.dev8+162.gf92ded2f (2019-12-16)
======================================
Features
--------
Core
~~~~
- Speed up loading dictionaries. (#1022)
- Be more restrictive with macro names: only accept valid identifier, so for example ``==`` is not handled like a macro anymore. (#1025)
User Interface
~~~~~~~~~~~~~~
- Add menu entry for opening the configuration directory ("File" => "Open config folder"). (#981)
- Automatically focus the input field and pre-select the …
```
> add towncrier support

- plover_build_utils/get_pip.py
- requirements.txt
- requirements_distribution.txt
- requirements_plugins.txt
- setup.cfg
* setup: drop support for Python 3.4 (EOL was March 18, 2019)
* update development requirements
* utils: update get-pip to pip 20.0.2
* plugins: update plover-plugins-manager to latest version
> Fix CI builds

- news.d/bugfix/1116.core.rst
- plover/system/__init__.py
Try loading from the (system) dictionaries root, not Plover's assets directory.
> system: fix wordlist loading for plugins

- .circleci/config.yml
CircleCI is rolling out a new UI and requires either a configuration update to v2.1 or to add a flag in the config. This PR adds the flag to the config.
> Enable CircleCI pipelines

- news.d/feature/989.core.rst
- plover/command/set_config.py
- setup.cfg
- test/test_command.py
Fixes #983.
I've added an engine command: SET_CONFIG, which allows you to set a Plover config setting using a stroke. Mirabai asked for a command that would change the add-translation window opacity, and this does that among other things. Adding entries like this into your dictionary will allow you to set values in the global configuration:
``"O*EP": "{PLOVER:SET_CONFIG:translation_frame_opacity,100}",``
``"TR*PB": "{PLOVER:SET_CONFIG:translation_frame_opacity,0}"``
Those change the add translation window opacity, but it should work for any config setting with a value that is type-castable from a string. With a little further work I could make it usable for the more complex config settings, possibly allowing you to do things like switch out dictionaries using this command.
> Add set config engine command

- plover_build_utils/pyqt.py
- plover_build_utils/setup.py
Rational:
- we already explicitly set connections in UI files
- auto-connections don't always work when there are multiple prototypes for the same signal' slot since Python functions are untyped
> Disable pyqt5 auto connections

- linux/appimage/apprun.sh
- linux/appimage/blacklist.txt
- linux/appimage/build.sh
- linux/packpack.sh
- plover_build_utils/trim.py
- windows/dist_blacklist.txt
* use the new Xenial image when using packpack
* switch to using linuxdeploy for AppDir creation
* trim some more unnecessary PyQt5 stuff, most notably the plugin manager does not use WebEngine anymore (which itself is provided as a separate wheel for recent PyQt5 releases)
> Update appimage build

- news.d/bugfix/1123.core.rst
- news.d/feature/1123.core.rst
- news.d/feature/1123.linux.rst
- plover/config.py
- plover/engine.py
- plover/main.py
- plover/oslayer/config.py
- plover/resource.py
- plover/steno_dictionary.py
- setup.py
- test/test_config.py
- test/test_engine.py
- simplify the load/save API
- ensure save operations are atomic
- save on config changes, instead of (always) on exit
- support `~/.config/plover` on Linux (it's given priority over `~/.local/share/plover`)
Closes #674, #915, and #1097.
> Improve config handling

- test/test_default_dict.py
The built-in dictionary tests currently account for the majority of the total test time, most of which is spent making sure each dictionary key is a valid series of strokes. There's no need to re-test identical strings, so packing them all into a set first speeds up *the entire test suite* by almost 50% on my machine.
I also flattened the closure in the other test which relied on some non-obvious scoping rules with a loop variable. 'object_pairs_hook=lambda x: x' makes json.load return the key/value pairs directly.
- no need for io import since open() is a builtin
- flatten function 'test_no_duplicates_categorized_files'
- optimize function 'test_entries_are_valid'
> Simplify default dictionary tests

- news.d/bugfix/1135.ui.rst
- plover/gui_qt/main.py
When programming plugins, it's easy to write code that terminates in a fatal error if something goes wrong. Indeed, plugins might even assume that any exceptions they raise will be handled by Plover. But Qt GUI code isn't necessarily this way, since it executes one level above the engine. A GUI tool plugin that raises an exception during dialog creation, for instance, will propagate it back to `MainWindow._activate_dialog`, which was called by a Qt signal on clicking the toolbar button. When that exception escapes, *the engine will never see it, and Plover will crash without warning*.
In fact, *any* exception that escapes a PyQt slot will have this effect by default. Any time a slot is called from a signal, that method is the bottom of the stack as far as Python can see. If an exception …
> Add default GUI exception trap

- news.d/bugfix/1139.core.rst
- plover/command/set_config.py
- plover/engine.py
The argument received by command plugins is no longer converted to lower case.
> Argument for custom command plugins should not be forced lowercase

- linux/README.md
- osx/README.md
- osx/dmg_resources/settings.py
- requirements.txt
- windows/README.md
Update dmgbuild and our own script to replace usage of biplist with plistlib to fix CI build.
No need for release notes or additional tests.
+ Very slight documentation update to make sure all platforms align on installing dependencies.
> Fix Mac CI

- osx/README.md
- requirements.txt
- windows/README.md
Updating to dmgbuild 1.4.1 solved the build, but introduced some new (harmless) errors. A patch was just released to address them.
Bonus: update documentation to be clear about using `python3` instead of `python` and also share that in order to build apps and dmgs, one needs python.org python.
> Update dmgbuild to suppress file not found errors

- .circleci/config.yml
- news.d/feature/1156.osx.rst
The oldest supported XCode version is now 9.4.1.
Fix #1155.
> circleci: update xcode version

- test/test_config.py
Ensure XDG_xxx environment variables don't screw up our isolation.
> tests: fix `test_config_dir` environment isolation

- plover/oslayer/winkeyboardcontrol.py
> oslayer/winkeyboardcontrol: fix Python 3.7 support

- plover/oslayer/winkeyboardcontrol.py
Followup to #1198 (contained):
- use `ctypes.wintypes` instead of rolling our own version of the Windows types
- declare `ctypes` functions prototypes to avoid potential issues
- improve error handling
> Improve `oslayer/winkeyboardcontrol`

- plover/oslayer/winkeyboardlayout.py
- plover/oslayer/wmctrl.py
Similarly to #1198 / #1199, this fix an issue with the keyboard layout support on Windows when using Python 3.8, fixed by declaring the signature of the `ctypes` functions we use.
Tested with my Windows 10 VM.
> oslayer/winkeyboardlayout: fix Python 3.8 support

- requirements_distribution.txt
- setup.cfg
For proper Python 3.9 support.
(Yes, I got the branch name wrong ¯\\_(ツ)_/¯).
> setup: update `python-xlib` requirement

- news.d/bugfix/1171.ui.rst
- plover/gui_qt/config_window.py
(see title.)
The bug only occur if the user installs more than one plugin and tries to enable/disable the one not on the first row.
> Fix wrong assertion to allow enabling/disabling extension plugins not on the first row

- news.d/feature/1157.core.md
- news.d/feature/1157.core.rst
- plover/formatting.py
- plover/gui_qt/add_translation_widget.py
- plover/meta/attach.py
- plover/meta/word_end.py
- plover/steno.py
- plover/translation.py
- setup.cfg
- test/test_blackbox.py
Prefix strokes only match at the beginning of a word: this is useful for orthographic theories with explicit spacing (like Melani). 
Needed for #987.
> formatting & translations: add support for prefix strokes

- news.d/bugfix/1188.core.md
- plover/steno_dictionary.py
Fixes a memory leak in the suggestions feature.
The leak only become apparent to me when I use the new console GUI. (normally I never use the suggestions window)
Remark: when I use the console GUI, I occasionally get a hang too. I guess it's caused by either dict rehash or garbage collection.
> Fix memory leak caused by defaultdict access in suggestions feature

- news.d/feature/1158.core.md
- plover/formatting.py
- plover/meta/conditional.py
- plover_build_utils/testing.py
- setup.cfg
- test/test_blackbox.py
#351  Summary of changes
Another change needed for full Melani support: conditional output, based on the text following a translation. The new syntax is `{=REGEXP/TRANSLATION_IF_FOLLOWING_TEXT_MATCH/TRANSLATION_IF_NOT}`. See blackbox tests for examples.
Needed for #987.
> formatting: look ahead support

- news.d/bugfix/1153.linux.rst
- plover/oslayer/xkeyboardcontrol.py
Uses `VoidSymbol` instead of `NoSymbol`, so the special case (explained in [this comment](https://github.com/jordansissel/xdotool/issues/97#issuecomment-711143601)) won't kick in.
`VoidSymbol` isn't defined in Xlib, so I have to hard code the constant.
Closes #1057, closes #1029 .
> Fix output capitalization issue on X

- .github/workflows/ci.yml
- .github/workflows/ci/workflow_context.yml
- osx/deps.sh
- plover/main.py
- plover_build_utils/functions.sh
- plover_build_utils/get_pip.py
- reqs/constraints.txt
- setup.cfg
- windows/dist_deps.sh
Note: I updated `hidapi` to `0.10.0.post1` and not `0.10.1` because the later breaks the AppImage build (it looks like linuxdeploy does not like the `manylinux2014` wheel).
> switch distributions to Python 3.8 and update requirements

- .github/workflows/ci/helpers.sh
- reqs/constraints.txt
Let's not pretend we support older versions, like PyQt5 does... and we might as well update to the latest version of PyQt5.
> target macOS 10.13 (High Sierra) or later

- setup.py
=> `plover-4.0.0.dev8+344.gfdf0c01-macosx-10.13-x86_64.dmg`
This should make the minimum supported macOS release and supported architecture clearer.
> setup: add target platform to macOS DMG filename

- news.d/bugfix/1219.ui.md
- plover/gui_qt/dictionary_editor.py
Don't delete the key first, so extra metadata (e.g. additional columns in an Excel dictionary) is not deleted.
> gui_qt/dictionary_editor: improve updating a translation

- test/test_config.py
> tests: fix `test_config_dir` environment isolation on Windows

- news.d/bugfix/1230.ui.md
- plover/gui_qt/config_window.py
Don't mutate the original configuration set, or changes won't be saved.
Closes #1180.
> gui_qt/config: fix configuring extension plugins

- news.d/bugfix/1163.linux.rst
- plover/oslayer/xkeyboardcontrol.py
Use a lock so that only one thread use the `_display` object of `KeyboardCapture` (in `plover/oslayer/xkeyboardcontrol.py`).
(there's no Python-xlib documentation about thread-safety (in fact there's hardly any documentation at all), so it's safer to assume that it isn't.)
Should close #1126 . (I toggle Plover with keyboard input machine repeatedly, and it tends to freeze without this change, and doesn't freeze so far with this change)
> Lock the display on use in KeyboardCapture for X

- plover_build_utils/functions.sh
- pyproject.toml
- reqs/constraints.txt
- reqs/packaging.txt
Explicitly set the build-backend, so we don't use the legacy setuptools' backend, and more tools (e.g. `check-manifest`) use PEP 517 support.
Improve packaging checks:
- use `build` to check PEP 517/518 support, building sdist and wheel
- don't run `setup.py check`: `twine check` already covers everything (including checking the description if `readme-renderer` is installed)
- drop the setuptools-scm dependency (not used, by us or `check_manifest`)
> Improve pep517 support and packaging checks

- news.d/bugfix/1248.ui.md
- setup.cfg
We don't want to include the generated catalogs in the source distribution, but we do need to include them in the wheel so they are part of the binary distributions.
> setup: fix inclusion of translations

- news.d/bugfix/1219.ui.md
- plover/gui_qt/dictionary_editor.py
This reverts commit 4f271959ee5cb5d59f79761175859e30b2dd3822. This use-case (only updating the translation) is not possible anymore after #1022 ([since an existing entry is deleted first](https://github.com/openstenoproject/plover/commit/d8a68ae0da40ce8f63fe60ea9400fbe5edda6156#diff-5a0d07941f5cd7ac11e809cd3dbf5d179a4249d9a63f53d52963efdba50122e6R126)), at least not without some contortions in the implementation.
> Revert "gui_qt/dictionary_editor: improve updating a translation"

- news.d/feature/1244.ui.md
- plover/gui_qt/dictionaries_widget.py
- plover/gui_qt/dictionaries_widget.ui
- plover/gui_qt/main_window.py
Alternative to #1149.
See commit messages for the detail of the changes.
Rational for 8dcda12d7257432a3edfb3937521b6bbfbdc5908, and allowing to create copies when multiple dictionaries are selected: with this PR and our support for read-only `assets:` resources, I think we should consider changing the system default dictionaries definition to:
```python
DEFAULT_DICTIONARIES = (
'user.json',
DICTIONARIES_ROOT + '/commands.json',
DICTIONARIES_ROOT + '/main.json',
)
```
This would result in:
- only `user.json` is (re-)created when missing
- the other 2 dictionaries are loaded read-only directly from the assets directory
This would make updating easier for users that don't change those dictionaries. And if you really want to edit those, you can always can now easily save a copy (and …
> Add dictionaries "save as..." support

- plover/dist_main.py
This is so someone does not end up with an invisible Plover running in headless mode (because that's the fallback if the Qt GUI cannot be loaded and no other one is available), possibly catching keyboard input. Note that it's still possible to override this choice using the `--gui` option.
> force the use of the Qt GUI when running from a distribution

- plover/gui_qt/main.py
Avoid getting spammed when using the debugger:
```
QCoreApplication::exec: The event loop is already running
QCoreApplication::exec: The event loop is already running
QCoreApplication::exec: The event loop is already running
QCoreApplication::exec: The event loop is already running
[...]
```
> gui_qt: remove PyQt input hook on start

- reqs/bootstrap.txt
- reqs/build.txt
- reqs/dist.txt
Since we don't directly depend on it at runtime, but may need it for bootstraping the distribution. Fix [an issue](https://aur.archlinux.org/packages/plover-git/#comment-802195) with the AUR package.
> reqs: move certifi to the boostrap requirements

- reqs/build.txt
- reqs/constraints.txt
With a workaround for the dreaded slowdowns when detaching:
```
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
```
I'd like more testing on this before making a PR to the dmgbuild project.
> osx: use custom version of dmgbuild

- .github/workflows/ci/skiplist_job_test.txt
Those were previously covered by the `plover/gui_*/*` exclusion pattern.
> ci: add translations catalogs to the test jobs' skiplist

- plover_build_utils/functions.sh
Of course we want the new changelog section to refer to the new release, not the old one...
> utils/functions: fix `release_prepare` helper

- plover/engine.py
They are meant to be executed under the protection of the engine loop.
> engine: make it clear that the output methods are internal

- plover/gui_qt/add_translation_dialog.py
- plover/gui_qt/add_translation_widget.py
- plover/gui_qt/config_window.py
- plover/gui_qt/dictionaries_widget.py
- plover/gui_qt/dictionary_editor.py
- plover/gui_qt/lookup_dialog.py
- plover/gui_qt/machine_options.py
- plover/gui_qt/main_window.py
- plover/gui_qt/paper_tape.py
- plover/gui_qt/suggestions_dialog.py
- plover/gui_qt/suggestions_widget.py
I just tried to build the latest version of Plover and got a screenful of import errors that I tracked down to imports of the _ translation macro from the generated GUI forms. There's already a circular dependency between the GUI modules and their Qt forms that is handled by having the forms code do imports at the bottom, but the extra import was too much.
After redirecting the imports, I got a clean build. It's possible that my particular combination of build tools contributed to the errors, but even if so, direct imports from the macro's definition in the root module seem like a better idea than indirect imports through dynamically-generated Python code.
EDIT: The build issue turned out to be with the UI code generator, but those imports still don't need to be routed through the stuff …
> Redirect indirect imports from GUI forms

- linux/appimage/blacklist.txt
- osx/app_resources/dist_blacklist.txt
- windows/dist_blacklist.txt
The main PyQt5 folder, with all the libraries and plugins, changed from `Qt` to `Qt5` in newer versions.
> Fix distribution blacklists

- linux/appimage/Dockerfile
- osx/deps.sh
- windows/dist_deps.sh
Note:
> According to the release calendar specified in PEP 569, Python 3.8.10 is the final regular maintenance release. Starting now, the 3.8 branch will only accept security fixes and releases of those will be made in source-only form until October 2024.
So we'll have to consider upgrading to 3.9 soon.
> update distributions to Python 3.8.10

- news.d/bugfix/1313.core.md
- plover/engine.py
Ignore missing extensions.
Closes #1305.
> engine: don't try to start missing extensions

- plover/gui_qt/main_window.py
> gui_qt/main_window: fix display lag on startup

- .github/workflows/ci/skiplist_default.txt
Those are only needed for generating the workflow itself.
> ci: add CI requirements to the default skiplist

- plover/scripts/main.py
When started with `python -m plover`.
> main: fix possible exception on restart

- tox.ini
Disable build isolation: we know the build requirements are available.
> tox: speed up `developpkg` phase

- .github/workflows/ci.yml
- .github/workflows/ci/workflow_context.yml
- linux/appimage/Dockerfile
- news.d/feature/1329.linux.md
Xenial reached end-of-life at the end of April, the [oldest supported LTS release is now Bionic](https://github.com/AppImage/appimage.github.io#checklist-for-submitting-your-own-appimage). The Github Actions' Xenial environment is also [deprecated](https://github.com/actions/virtual-environments/issues/3287) and will be removed on September 20, 2021..
Closes
> Update AppImage to Bionic

- NEWS.md
- news.d/api/1284.break.md
- news.d/api/1302.new.md
- news.d/bugfix/1302.core.md
- news.d/bugfix/1313.core.md
- news.d/bugfix/1314.ui.md
- news.d/feature/1284.core.md
- news.d/feature/1306.core.md
- news.d/feature/1329.linux.md
- plover/__init__.py
So plugin authors can depend on it (particularly for dictionary plugins).
> Bump development version to dev10

- index.html
Change "rhymes with hover" to "rhymes with lover".
It's a common criticism of the page since it doesn't match with everyone's accents (which can then lead to being turned off of Plover itself, because not being applicable to everyone's accents and writing styles is a big concern).
I've changed this to "lover" since this matches the [wiki](https://github.com/openstenoproject/plover/wiki) and seems to not have as many issues.
> Change hover to lover

- reqs/constraints.txt
A minor bugfix release: https://www.riverbankcomputing.com/news/PyQt_v5.15.6_Released.
> reqs: update `PyQt5` to latest bugfix release

- news.d/bugfix/1463.dict.md
Currently, this entry gets misparsed as a command and thus throws an
exception. Change it to do a raw attach as suggested in
https://github.com/openstenoproject/plover/issues/1407#issuecomment-914881597
Fix #1407.
Thanks @sammdot 
`{:^}` is parsed as the command `^` incorrectly.
Closes
> dictionary: fix KHR*PB stroke

- news.d/feature/1451.ui.md
- plover/gui_qt/paper_tape.py
Fix regression created by #1308: the paper mode header was no longer getting updated (e.g. when using a system other than the default).
> Fix paper tape regression

- reqs/constraints.txt
- reqs/test.txt
- test/gui_qt/test_dictionaries_widget.py
- test/test_engine.py
- test/test_keyboard.py
- tox.ini
* fix tox lightweight tests environment so the QT GUI tests can be run
* add `mock` to the tests dependencies: the standard library version provided by Python <= 3.7 is too old
>  Fix QT GUI tests

- plover/dictionary/rtfcre_dict.py
Looks like the document is gone from the original site...
> dictionary/rtfcre: fix link to RTF/CRE spec

- news.d/feature/1452.core.md
- plover/steno.py
- plover/translation.py
- plover_build_utils/testing/blackbox.py
- reqs/constraints.txt
- reqs/dist.txt
- test/test_blackbox.py
Ensure instances stay valid after a system change. See the blackbox tests for details.
Closes #1448.
> steno: fix `Stroke` implementation

- plover_build_utils/setup.py
- setup.py
Fix deprecation warning:
```
setup.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
from distutils import log
```
> Fix setuptools warning

- news.d/bugfix/1481.ui.md
- plover/gui_qt/suggestions_widget.py
Optimize the delegate' `sizeHint` implementation and cache calls to it.
Closes #1477.
> Speedup suggestions widget

- plover/i18n.py
- plover/oslayer/config.py
- plover/registry.py
- plover/resource.py
- plover_build_utils/check_requirements.py
- plover_build_utils/testing/steno_dictionary.py
- test/test_resource.py
Salvage parts of #1488: do not switch to `importlib_metadata`, keep using `pkg_resources` in `scripts.main` and for the `registry` implementation, remove other uses.
> Partially drop the dependency on `pkg_resources`

- news.d/bugfix/1495.windows.md
- windows/installer.nsi
Otherwise, if the installer is running as privileged (when installing for all users), Plover will be launched as admin, which can create issues later (e.g. permission errors with the controller's pipe).
> windows: drop launch option from installer's final page

- news.d/bugfix/1504.core.md
- plover/engine.py
- test/test_engine.py
Ensure we're not using the initial (disabled) state.
> engine: fix running state

- news.d/bugfix/1507.core.md
- news.d/bugfix/1507.windows.md
- plover/scripts/main.py
There were only executed on restart...
Partially address #1502.
~- [ ] Changes have tests~
> main: fix exit handlers not getting always executed

- plover_build_utils/download.py
So error messages don't get swallowed when using `var="$(python -m plover_build_utils.download […])"` in shell scripts.
> utils/download: print errors on stderr

- linux/README.md
- linux/appimage/Dockerfile
- linux/appimage/build.sh
- news.d/feature/1496.linux.md
- plover/oslayer/log_dbus.py
- reqs/constraints.txt
- reqs/dist_extra_log.txt
- remove dependency on the `dbus-python`
- notification messages are now sent asynchronously
- work even if the notifications service does not support type introspection
- more robust: if the notification service goes down, calls to the handler won't raise an exception
Close #1490.
> oslayer/log_dbus: use `libdbus` directly

- news.d/feature/1491.core.md
- plover/steno.py
- plover/system/__init__.py
- plover/system/english_stenotype.py
- reqs/constraints.txt
- reqs/dist.txt
- test/test_rtfcre_dict.py
- test/test_steno.py
Support the arbitrary placement of the number sign when parsing steno. 
Closes #1486.
> system/english_stenotype: improve RTF/CRE compatibility

- news.d/feature/1513.core.md
- plover/translation.py
- test/test_translation.py
With the following dictionary stacks:
- user:
```json
{
"EUPB/EBGS/PEPBS/EUF": "inexpensive",
}
```
- commands:
```json
{
"PHROLG": "{PLOVER:TOGGLE}"
}
```
- main:
```json
{
"A*/KR*/*E/T*/O*/P*/H*/*EU/HR*/*EU/KR*": "acidophilic",
"OBLG": "okay",
"-RBGS": "{,}",
"HRET": "let",
"AES": "{^'s}",
"SAOE": "see",
"HOU": "how",
"PHAEPB": "many",
"HRAOUP": "lookup",
"TP-R": "for",
"SUFBGS": "suffix",
"-G": "{^ing}",
"-S": "{^s}",
"-D": "{^ed}",
"-Z": "{^s}",
}
```
Writing `OBLG -RBGS HRET AES SAOE HOU PHAEPB HRAOUP -S TP-R SUFBGSZ`, the last stroke results in the following dictionary collection lookups:
```
/SUFBGSZ in user, main
SUFBGSZ in user, cmds, main
/-RBGS/HRET/AES/SAOE/HOU/PHAEPB/HRAOUP/-S/TP-R/SUFBGSZ/SUFBGSZ
-RBGS/HRET/AES/SAOE/HOU/PHAEPB/HRAOUP/-S/TP-R/SUFBGSZ/SUFBGSZ in main …
```
> translation: avoid unnecessary lookups

- news.d/bugfix/1527.ui.md
- plover/gui_qt/add_translation_dialog.py
- plover/gui_qt/add_translation_widget.py
Enable the "Ok" button when the dialog "strokes" field is automatically populated from the latest untranslate.
Closes #1526
> gui_qt/add_translation: fix #1526

- news.d/feature/1534.ui.md
- plover/gui_qt/main.py
Qt messages (like a warning when calling `setStyleSheet` with an invalid stylesheet) are currently printed to stderr, with no user feedback. Capture and reroute them through our standard logger.
> gui_qt/main: capture and log Qt messages

- news.d/feature/1514.ui.md
- plover/gui_qt/main.py
Add support for styling the Qt GUI: automatically load and apply a custom stylesheet from `plover.qss` (in the configuration directory) when present.
Closes #1514.
> add custom stylesheet support for the Qt GUI

- tox.ini
It's `basepython`, not `base_python`, and it does not work as expected, so just get rid of it.
> tox: remove invalid directive

- MANIFEST.in
- reqs/test.txt
- test/gui_qt/test_dictionaries_widget.py
- test/py37compat.py
- test/test_engine.py
- test/test_keyboard.py
To make it easier to drop support for Python<=3.7 when the time comes.
> test: mark code necessary for Python<=3.7 compatibility

- news.d/feature/1539.ui.md
- plover/gui_qt/paper_tape.py
- plover/gui_qt/suggestions_widget.py
- plover/gui_qt/utils.py
Change the selection mode for the paper tape / suggestions widget to "extended" (allow selecting multiple items, support shift/control), and allow copying the current selection to clipboard using the standard copy shortcut.
> add support for copying the paper tape / suggestions widget selection to clipboard

- news.d/bugfix/1545.linux.md
- plover/oslayer/linux/log.py
- plover/oslayer/linux/log_dbus.py
Better ctypes type checking, and raise an exception if the call to `dbus_bus_get` failed: this ensure Plover will fallback to the Qt logger.
Closes #1544
> improve D-Bus log handler

- news.d/bugfix/1547.core.md
- plover/engine.py
- test/test_engine.py
Don't try to undo an empty state.
> engine: fix possible `clear_translator_state` issue

- news.d/bugfix/1546.ui.md
- plover/gui_none/add_translation.py
Fixes a couple of unreported issues in the non_gui implementation for adding entries to a dictionary.
1.  Strokes are incorrectly sliced. Leaving out the initial one and instead including the stroke for {PLOVER:ADD_TRANSLATION} [fixed in 37fa63d636071688fb475bfa7608ce144cd5baea]
2. Input isn't cleared out correctly after each stage of entry (stroke, translation). Leaving the first output in the active text-box [fixed in 37fa63d636071688fb475bfa7608ce144cd5baea]
3. Aborting the dictionary addition without entering any strokes causes an AssertionError (see log below) [fixed in 6ef18d0006536c1e73cc14743ff3fc17444df41e]
```
2022-08-07 14:17:48,654 [Thread-1-engine] ERROR: hook 'add_translation' callback <bound method AddTranslation.trigger of <plover.gui_none.
Traceback (most recent call …
```
> Fix bugs in gui_none/add_translation

- doc/developer_guide.md
- news.d/feature/1592.core.md
- tox.ini
Updates tox.ini configuration to support building with newer [tox 4](https://tox.wiki/en/latest/upgrading.html).
This is not backwards compatible with tox version 3.
I've successfully build & run tests on Linux, this will need testing on Windows and Mac
> Update tox to version 4

- .github/workflows/ci.yml
- .github/workflows/ci/helpers.sh
- .github/workflows/ci/workflow_context.yml
- .github/workflows/ci/workflow_template.yml
- news.d/feature/1598.osx.md
- news.d/feature/1598.windows.md
The goal of this PR is to fix all deprecation warnings that we currently have in our GitHub Action runs, see for example [the latest run on master](https://github.com/openstenoproject/plover/actions/runs/4395109518):
* replaces the deprecated `set-output` command, see [GitHub Blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
* updates all imported GitHub Actions such as actions/cache to remove related deprecation warnings
* updates deprecated macos-10.15 version in GitHub Actions
* updates windows-2019 version in GitHub Actions because why not
See [this run](https://github.com/openstenoproject/plover/actions/runs/4396816672) which does not show any warnings.
> Update commands and OS versions in GitHub Actions

- plover/machine/base.py
- plover/machine/geminipr.py
- plover/machine/passport.py
- plover/machine/procat.py
- plover/machine/stentura.py
This removes some code duplication. I'm not yet sure if it's worth the effort (e.g. would we want to update the plugin documentation accordingly?).
As this is a refactoring, it technically should not require any new tests.  However, from what I understand only `test/test_passport.py` tests the relevant code right now.
Regarding news fragments + docstring, is this relevant for the plugins api?  If yes, I guess we would want both?
> plover/machine/*: DRY up / remove code duplication

- news.d/bugfix/1571.ui.md
- plover/gui_qt/add_translation_widget.py
Setting the stylesheet resets the palette colors to the system default. For the base color (which was used by the span for the formatted translation & raw stroke text), that'd mean that it'd be reset to `#ffffff`.
While setting the palette from the stylesheet could be done, it's much simpler to instead let the formatted text inherit the background color (i.e. removing the explicit setting of the background color).
Closes #1569
> Fix "Add Translation" formatted translation & raw strokes always using a white background color

- plover/gui_qt/add_translation_widget.ui
Closes #1624.
Looks like the change was made in #1308.
I believe reordering the tab stops should not affect the accessibility issues, but it would again be a breaking change. Any opinion?
> Revert original tabstop order of fields in add translation widget

- news.d/feature/1611.core.md
- plover/gui_qt/config_keyboard_widget.ui
- plover/gui_qt/machine_options.py
- plover/machine/keyboard.py
- test/test_command.py
- test/test_config.py
- test/test_keyboard.py
See title.
Refer to http://plover.stenoknight.com/2021/09/qmk-extensions-for-hobbyist-stenoboards.html for some detail what first-up chord send is -- basically this allow you to, e.g. if you have STPH-G bound to [→] (`{#Right}{^}`), then you can hold down STPH and repeatedly press -G to press [→] multiple times.
--------
Later it may be useful for things like "repeatedly send a chord with frequency X if it's held for longer than time Y", so making a check box doesn't feel like the best idea.
Currently it gives an error (that can only be fixed by clicking the refresh button) if both options are checked. Maybe it's better to either make a combo box or make the GUI automatically untick the other button if one is ticked (this may be confusing though)?
There's a quirk: currently if I hold down …
> First-up chord send for keyboard machine

- news.d/bugfix/1560.ui.md
- plover/machine/base.py
- test/test_machine.py
When the *machine thread* dies due to an unhadled exception then indicate this to the engine (and by extension to the user) by setting the machine state to "disconnected".
This is a first step.  Possible follow-ups:
1. We may choose to handle `serial.serialutil.SerialException` more explicitly as a "disconnect" (say, not even print a stack trace to `stderr`).
2. What I really want from a users perspective is that the machine re-connects automatically (I think it's feasible to do so, stay tuned for a follow-up PR).
3. For `SerialStenotypeBase` specifically, we also want to close the serial port on unhandled exceptions.
Even if we do (1) and/or (2) later, I think we still want this PR as a fallback for arbitrary exceptions.
I will have a separate PR for (3), but again, I think this PR …
> Update machine state on unhandled exceptions

- .github/workflows/ci.yml
- .github/workflows/ci/workflow_context.yml
- doc/developer_guide.md
- news.d/api/1634.break.md
- reqs/test.txt
- setup.cfg
> Drop support for Python 3.7

- news.d/api/1633.new.md
- news.d/feature/1633.core.md
- plover/config.py
- plover/engine.py
- plover/gui_qt/config_window.py
- plover/oslayer/linux/keyboardcontrol_x11.py
- plover/oslayer/osx/keyboardcontrol.py
- plover/oslayer/windows/keyboardcontrol.py
- plover/output/__init__.py
- plover/output/keyboard.py
- test/test_config.py
- test/test_engine.py
This is a continuation of #1584 (and by extension, #1132), primarily refactoring the delay logic so it's not all repeated in the individual OS layer implementations.
Closes #1584; closes #1132.
> Add configurable key press delay

- news.d/bugfix/1636.core.md
- plover/machine/base.py
In addition to the changes from #1560, this PR closes a serial port on error to handle this issue from #1054:
> Now an exception in the run method is reported as an error to the system
and additionally the SerialStenotypeBase class does close the com port on
error.
> 
> **Otherwise the com port resource might still be taken by plover upon
reconnect of the writer, and a different com port might be taken by the OS
and plover might not be able to reconnect to that machine.**
Closes #1054.
> Close serial port when disconnected to ensure clean reconnection

- osx/README.md
The old link is dead: https://web.archive.org/web/20170401143114/https://support.apple.com/kb/ph18391?locale=en_US
Also, I guess there was a change toward calling these "accessibility (features/permissions)" rather than "assistive devices"? I don't see the word "assistive device" anymore in the new docs, so I updated the wording in the README as well.
> Update link about accessibility permissions

- .github/workflows/ci.yml
- .github/workflows/ci/workflow_context.yml
- .github/workflows/ci/workflow_template.yml
- reqs/constraints.txt
Fixes the currently broken GitHub actions (see e.g. [this run](https://github.com/openstenoproject/plover/actions/runs/12678789290)):
1. Bump the GitHub action runner macOS version since macOS-12 is deprecated, resulting in the test being skipped
2. Bump the ubuntu version to 24.04 since it's not causing issues (Windows 2025 does create issues so leaving that out for now)
3. Bump twine to 3.7.0 to support metadata 2.2 which is otherwise breaking the packaging build
4. Bump pkginfo to 1.8.1 which is required by twine 3.7.0
5. Bump the GitHub actions versions to remove deprecation warnings
6. Update when the GitHub actions are triggered to prevent double executions (both triggered by `push` and `pull_request`)
I don't think it makes sense to add a news fragment since this is a technical …
> Fix GitHub actions

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- doc/releases.md
- doc/translation_language.md
As in the title. Should be harmless.
> Rename reference to 'master' branch to 'main'

- news.d/feature/1700.ui.md
- reqs/constraints.txt
Bump plover-plugins-manager to 0.7.2 to include changes like https://github.com/openstenoproject/plover_plugins_manager/pull/21.
Installed the macOS DMG file created via the GitHub actions (on M1 mac). The install via git feature works (tested with [plover2cat](https://github.com/greenwyrt/plover2CAT)).
> Bump plover-plugins-manager to 0.7.2

- .github/workflows/ci.yml
- .github/workflows/ci/helpers.sh
- .github/workflows/ci/workflow_template.yml
- doc/ci.md
- pyproject.toml
Removes the logic that generates continuous GitHub releases. See [this discussion](https://discord.com/channels/136953735426473984/144999734254370816/1361076524278747136) on Discord.
> Remove continuous release logic

- .github/workflows/ci.yml
- .github/workflows/ci/workflow_context.yml
- news.d/bugfix/1717.linux.md
Downgrade Linux CI build to ubuntu-22.04 to use a lower GLIBC version since some Linux distributions don't support `GLIBC_2.38`.
Closes #1710
> Downgrade Linux CI build to ubuntu-22.04

- .github/workflows/ci.yml
- .github/workflows/ci/helpers.sh
- .github/workflows/ci/workflow_template.yml
- plover_build_utils/functions.sh
Adds the `tags` push trigger in our GitHub actions CI. In https://github.com/openstenoproject/plover/pull/1716, `tags-ignore` was removed and thereby no tag pushes were registered anymore. This, however, is important for building releases.
> Add tags push trigger to CI

- news.d/bugfix/1724.linux.md
- plover/oslayer/linux/keyboardcontrol_uinput.py
There was an issue where keyboards that had the ability to control the mouse were not able to be recognized as keyboards in the uinput module. This pr fixes that by checking for keyboard keys instead.
-  ~~[ ] Changes have tests~~
> Fixed certain keyboards not getting detected in the uinput module

- plover/oslayer/linux/keyboardcontrol_uinput.py
As mentioned in https://github.com/openstenoproject/plover/issues/1707 , this tries to use hardware key as much as possible.
Things like `?` or `*` (which requires shift key) doesn't work yet. I haven't tested with layouts other than Qwerty.
> Add more keys to uinput output

- plover/scripts/main.py
As in the title. This happens when Plover starts up and detect another process exists.
The issue is the following: when the other process exits at a certain time (after the connection is made but before the `send_command` is sent… so race condition) then `ConnectionResetError` is sent.
I see this in practice with a stroke defined by `{PLOVER:SHELL:xterm -e tmux new bash -c "sleep 0.5s; setxkbmap us; plover --log-level info; bash" &}{PLOVER:QUIT}` (you can see what it does easily — quit Plover then start a new instance after 0.5 second — although Plover can be slow to exit, so let's say it exits after 0.6 seconds then the above happens. In order to reproduce the error you may need to tune the `0.5s` a bit)
> Also catch ConnectionResetError

- news.d/bugfix/1728.linux.md
- plover/oslayer/linux/keyboardcontrol_uinput.py
Makes uinput module wait for all keys on each input device to be released before grabbing the device. This prevents keys from being stuck when keys are held while Plover is starting.
Device grabbing was moved from `_run` to `start` to show that the keyboard is still connecting in the UI while waiting for keys to be released (`self._running` is only set when keys are grabbed)
> Wait for all keys to be released before grabbing

- news.d/bugfix/1729.linux.md
- plover/oslayer/linux/keyboardcontrol_uinput.py
Improve uinput exception handling by wrapping the keyboard capture loop in a try finally. All devices are ungrabbed in the finally block so that exceptions do not block all grabbed input devices. Currently, if an exception occurs in `_run`, the loop exits and no device inputs are handled. This issue can be reproduced by having multiple keyboards and unplugging one.
A possible UI improvement is to show an error/disconnected state when an exception occurs. I haven't figured a clean way to do this yet.
> UInput: ungrab devices on exception

- news.d/bugfix/1731.linux.md
- plover/oslayer/linux/keyboardcontrol_uinput.py
When inputting Unicode with uinput the code now uses space to finalize the Unicode character instead of enter.
Closes #1725
> Send space instead of enter to finalize unicode with uinput

- news.d/bugfix/1739.core.md
- plover/plugins_manager/registry.py
This makes it possible to uninstall a plugin that is listed as unsupported by not overwriting the `installed` status if the plugin is unsupported.
> Allow uninstall of unsupported plugins

- news.d/bugfix/1740.core.md
- plover/gui_qt/add_translation_widget.py
- plover/gui_qt/info_browser.py
- plover/gui_qt/main.py
- plover/gui_qt/main_window.py
- plover/gui_qt/paper_tape.py
- plover/gui_qt/paper_tape.ui
- plover/gui_qt/suggestions_dialog.py
- plover/gui_qt/utils.py
- plover/system/__init__.py
Fixes warnings similar to this one: `WARNING: Qt: Populating font family aliases took 67 ms. Replace uses of missing font family "Verdana,Geneva,DejaVu Sans,sans-serif" with one that exists to avoid this cost. `
Affected are:
* Add Translation (default font)
* Paper Tape (default font)
* Info Browser of the Plugins Manager (fonts specified in SVG images that are linked in the plugin README)
Also disables the "pin window to the top" functionality on Wayland since it's not supported there.
Tested on macOS, Windows, and Linux.
> Fix missing font family warnings

- news.d/feature/1746.linux.md
- plover/config.py
- plover/gui_qt/config_window.py
- plover/oslayer/linux/keyboardcontrol_uinput.py
Adds `dvorak` as a choice in the keyboard layouts dropdown in the options screen for uinput users.
Provides a temporary workaround until a proper solution emerges for #1726.
> Add dvorak keyboard layout

- news.d/bugfix/1750.core.md
- reqs/constraints.txt
Updates the plugins manager to version 0.7.9 as well as other Python dependencies that are needed to make the plugins manager work, mainly regarding the parsing of plugin version numbers.
Tested successfully on Windows, Linux, and macOS.
> Fix python dependencies for plugins manager

- news.d/feature/1765.linux.md
- plover/oslayer/linux/keyboardcontrol_uinput.py
Refactor UInput start and cancel code to simplify error handling and remove the unused `_running` variable.
Closes
> Uinput: Refactor initialization and cleanup
